### ISSUE TITLE
Unzip convenience functions

### ISSUE THREAD

**Issue by corey-nm** [neuralmagic/sparseml#1011]
1. Add zoo_model.unzip() which unzips everything. (Users can still call unzip per sub directory if they want)
2. add `unzip=False` to download params so you can call `zoo_model.download(unzip=True)`

_Originally posted by @corey-nm in https://github.com/neuralmagic/sparseml/pull/927#discussion_r951406738_

**Comment by dbogunowicz** [comment]
This is a good one!

**Comment by jeanniefinks** [comment]
It appears this has been resolved through #927 so I will close out this issue.
