### ISSUE TITLE
version conflict in colab

### ISSUE THREAD

**Issue by miladlink** [neuralmagic/sparseml#1034]
Hi
thanks to neuralmagic team for great repo
i was using this repo for Sparse Transfer Learning With YOLOv5 in google colab
but after installation ddint workout any commands including !parseml.yolov5.train ... or !sparseml.yolov5.export_onnx ... because of version conflict.
please help me to use this repo in google colab invironment

**Comment by rahul-tuli** [comment]
Hi @miladlink; Hopefully this issue is resolved now, if you still see a issue while exporting, kindly open a new issue with the relevant stack trace. Closing this one out for now.
