### ISSUE TITLE
epoch flag does not override default epoch count of 52

### ISSUE THREAD

**Issue by d-smit** [neuralmagic/sparseml#1038]
Hello, I was unable to change the number of training epochs after adding these flags to my training command:

!sparseml.yolov5.train \
--epochs 100 \
--batch-size 16 \
--imgsz 416 \
--data yolov5/data2.yaml \
--cfg models_v5.0/yolov5s.yaml \
--weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer \
--hyp data/hyps/hyp.finetune.yaml \
--recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer

My model successfully trains but for the overridden amount of 52 epochs. Can this be changed? 

I am running on Google Colab (free version) with the latest sparseml version downloaded via pip today (15/9/22)

Thanks in advance.

**Comment by KSGulin** [comment]
Hi @d-smit, the number of epochs in the recipe always takes precedent. I recommend downloading the recipe or copying it over (_you can view the recipe on the model's [SparseZoo card](https://sparsezoo.neuralmagic.com/models/cv%2Fdetection%2Fyolov5-s%2Fpytorch%2Fultralytics%2Fcoco%2Fpruned_quant-aggressive_94) by clicking on the transfer_learn.md button below the "recipes" section_) and modifying the epochs set in there. Note that it's not quite as simple as overriding `num_epochs`, as you'll want to change at least `quantization_start_epoch` as well, if not other fields. Note we generally see best performance with 2 epochs of QAT at the end of training, but feel free to experiment.
