### ISSUE TITLE
sparssified yolov5s does not speed up rather to yolov5s .

### ISSUE THREAD

**Issue by mpanahish** [neuralmagic/sparseml#1087]
I'd use below code to transfer learning yolov5 on my custom dataset
`!sparseml.yolov5.train --data {dataset.location}/data.yaml  --cfg models_v5.0/yolov5s.yaml \
                       --hyp data/hyps/hyp.finetune.yaml \
                       --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --batch 16\
                       --epochs 100  --imgsz  416 --save-period 5`
and after that,  export to onnx

`!sparseml.yolov5.export_onnx --weights epoch60.pt 
                            --simplify
` 

**Expected behavior**
I expect this onnx file give faster  inference than  yolov5s traind on same custom data which exported to onnx.

but i get this result for sparssified yolov5s : 
on CPU: 338 ms
on GPU: 13 ms

and this for yolov5s :
on CPU: 345 ms
on GPU: 12 ms

**Comment by KSGulin** [comment]
Hi @mpanahish, you'll want to add the argument `--weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer` to your training command. You're on the right track by using sparse transfer learning to train your sparse model. The recipe that you're using assumes you're starting with an already sparse model and maintains the sparsity level while fine-tuning on your dataset (the `recipe_type=transfer` query argument specifies this), so adding the argument above will set your starting model as the sparse one. 

Closing the issue, but feel free to re-open if you're seeing any more speedup issues!

**Comment by mpanahish** [comment]
> Hi @mpanahish, you'll want to add the argument `--weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer` to your training command. You're on the right track by using sparse transfer learning to train your sparse model. The recipe that you're using assumes you're starting with an already sparse model and maintains the sparsity level while fine-tuning on your dataset (the `recipe_type=transfer` query argument specifies this), so adding the argument above will set your starting model as the sparse one.
> 
> Closing the issue, but feel free to re-open if you're seeing any more speedup issues!

I did your comment and retrain my model but nothing changed !
time performance not changed !

my training code : 
`!sparseml.yolov5.train --data {dataset.location}/data.yaml  --cfg models_v5.0/yolov5s.yaml \
                       --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer \
                       --hyp data/hyps/hyp.finetune.yaml \
                       --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --batch 16\
                       --epochs 100  --imgsz  640 --save-period 5\
                       --project /content/drive/MyDrive/--name=exp`
