### ISSUE TITLE
set final_sparsity=0.45, after 50 epochs, the sparsity of each layer is about 0.39

### ISSUE THREAD

**Issue by yueyunqingwu** [neuralmagic/sparseml#1117]
hi, everyone, when i used sparseml to sparse my model, i got a problem. 
after finished training based on a pretrained checkpoint, the sparsity of each layer is about 0.39, much less than the final_sparsity 0.45.
my recipe is as follow:

version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 50.0

  - !GMPruningModifier
    params:
      __ALL_PRUNABLE__
    init_sparsity: 0.05
    final_sparsity: 0.45
    start_epoch: 1.0
    end_epoch: 50.0
    update_frequency: 0.5
    global_sparsity: False
    inter_func: cubic
    leave_enabled: True
    mask_type: unstructured

my training strategy is as follow:
optimizer:
  name: AdamW
  lr: 0.0001
  weight_decay: 0.05
lr_schedule:
  name: CosineAnnealingLR
  T_max: 50
  eta_min: 0.00005

Has anyone had a similar problem? thanks

**Comment by bfineran** [comment]
Hi @yueyunqingwu what training script are you using? Unexpected final sparsity can be a result of steps per epoch being out of sync with the actual number of update steps that occur.

**Comment by jeanniefinks** [comment]
@yueyunqingwu 
Since some time has passed, we'll go ahead and close this issue. But if you're able to supply the requested info, please do! We're happy to assist. Thank you.
Jeannie / Neural Magic
