### ISSUE TITLE
Directory with recipes

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#120]
Hi!
I've been trying to run some `sparseml` examples from the `/scripts/pytorch_vision.py` but I can't find the directory with recipes. For example: `~/sparseml_recipes/pruning_resnet50.yaml`, `~/sparseml_recipes/pruning_mobilenet.yaml`. Looks like the `sparseml_recipes` directory doesn't exist at all.

**Comment by markurtz** [comment]
Hey @eldarkurtic, definitely agree it's not easy right now to find recipes. We've moved them all over to the SparseZoo to enable easier maintenance, expansion, and searching. For the next release we'll be putting up a UI to more easily explore and view them along with some fixes to the SparseZoo api to load recipes directly through Python. For now, though, the  available ones can be found [here](https://docs.neuralmagic.com/sparsezoo/recipes.html).

We can also add some common recipes as examples to the documentation. Are there any in particular you think would be good to put in there?

**Comment by eldarkurtic** [comment]
Thanks for the link for recipes. I would suggest adding recipes mentioned as examples in the `pytorch_vision.py`, so that the `sparseml` repo is self-contained (`pruning_resnet50.yaml`, `pruning_mobilenet.yaml`). They could serve as a template for quickly creating new recipes and for a gentle introduction to the `sparseml` repo (without exploring any additional repositories).

**Comment by markurtz** [comment]
Thanks for the feedback @eldarkurtic, we'll get some examples added in at some point before our next release later this month. We'll keep this issue open until that code is able to land.
