### ISSUE TITLE
No matching distribution found for sparsezoo~=0.2

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#121]
**Describe the bug**
Following the *DEVELOPING.md* guidelines results with the following errors after cloning the repo and running `python3 -m pip install -e ./[dev,torch]` in the dedicated conda environment.
```shell
ERROR: Could not find a version that satisfies the requirement sparsezoo~=0.2 (from sparseml[dev,torch])
ERROR: No matching distribution found for sparsezoo~=0.2
```

**Expected behavior**
Project installed in the editable mode.

**Environment**
Include all relevant environment information:
1. OS: Debian 4.19.171-2 (2021-01-30) x86_64
2. Python version: 3.{6,7,8,9}
3. SparseML version or commit hash: latest at the main branch (`10c112135466176fac4a3b713fd354d50ba53ddc`)

**To Reproduce**
Exact steps to reproduce the behavior:
```shell
git clone https://github.com/neuralmagic/sparseml.git
cd sparseml
python3 -m pip install -e ./[dev,torch]
```

**Comment by markurtz** [comment]
Hey Eldar, thanks for filing this! We were mid-release unfortunately so main was left in a broken state. The 0.2.0 release has gone out now, so everything should be back to normal. We'll be sure to fix the process for next time to make sure main is still functioning while waiting on release!

**Comment by eldarkurtic** [comment]
Thanks for the quick update. It works now.
