### ISSUE TITLE
Seeing a `TorchScript: export failure: _Map_base::at` when trying to export sparsified yolov5 to torchscript format

### ISSUE THREAD

**Issue by hem-dash** [neuralmagic/sparseml#1248]
**Describe the bug**
Running the following command
```sh
sparseml.yolov5.export_onnx --weights /dbfs/FileStore/hemanthchittanuru/sparseyolo/exp/weights/best.pt --dynamic --include torchscript
```
is leading to the following error: `TorchScript: export failure: _Map_base::at``

**Expected behavior**
Expected a `.torchscript` file to get created, like the `.onnx` file

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]:
2. Python version [e.g. 3.7]: 
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.2.0
4. ML framework version(s) [e.g. torch 1.7.1]: torch.1.9.0+cu11
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**
Exact steps to reproduce the behavior:
Train a model, or loading an existing model, and try exporting it to torchscript using the `export.py` in yolov5.

**Errors**
```
TorchScript: starting export with torch 1.9.0+cu111...
TorchScript: export failure: _Map_base::at
```

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by KSGulin** [comment]
Hi @hem-dash,

Thanks for reporting this issue. Torchscript export is not a pathway that we're supporting and we recommend exporting to ONNX instead. The optimizations that SparseML performs on sparsified models during export are targeted at ONNX and unfortunately don't readily transfer to Torchscript.

In general, you'll get the most of the sparsity-enabled speedup from running your model with the [DeepSparse](https://github.com/neuralmagic/deepsparse) engine, which executes on ONNX graphs. 

Going to close the issue, but feel free to re-open and follow up here if you have any remaining questions!
