### ISSUE TITLE
CUDA error: out of memory while training on WSL2

### ISSUE THREAD

**Issue by dokluch** [neuralmagic/sparseml#1275]
**Describe the bug**
CUDA errors while training under WSL2 + Ubuntu 20.04
No processes shown under nvidia-smi, memory is pretty much free

**Expected behavior**
Vanilla Yolov5 trains correctly

**Environment**
1. Windows 11 / WSL2 + Ubuntu 20.04
2. Python version: 3.8
3. SparseML version or commit hash: 6895c0911756acf298c57157d59a803d4d229a99
4. ML framework version - torch 1.12.1
5. Other relevant environment information Nvidia A6000,  NVIDIA-SMI 525.60.07    Driver Version: 527.27       CUDA Version: 12.0

**To Reproduce**
```
sparseml.yolov5.train   --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none   --data /mnt/e/custom.yml   --hyp data/hyps/hyp.scratch.yaml   --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94 --batch 32
```

**Errors**
```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by bfineran** [comment]
Hi @dokluch at what point in training do you run into the cuda OOM issue? and what batch size are you running at?

**Comment by jeanniefinks** [comment]
Hello @dokluch 
Since some time has passed, we'll go ahead and close this issue. But if you're able to supply the requested info, please do! We're happy to assist. Thank you.
Jeannie / Neural Magic
