### ISSUE TITLE
Installation link is broken

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [neuralmagic/sparseml#1390]
Hi,

The link you provided on your github page that takes you to instalation information page is broken. 
`https://docs.neuralmagic.com/sparseml/source/installation.html`
can you please fix this. 

UPDATE:
I have found this page though through google.
`https://docs.neuralmagic.com/get-started/install/sparseml`

Thank you for this great repo

**Comment by jeanniefinks** [comment]
Thank you @SuroshAhmadZobair!
I have corrected the updated link and merged the change.

If you haven't already, please ⭐ our repos; we appreciate the community support! 
Best wishes, Jeannie / Neural Magic
