### ISSUE TITLE
No module named 'sparseml.yolov8'

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [neuralmagic/sparseml#1391]
Hi,

When i run sparseml.ultralytics.train --help, i get:
`ModuleNotFoundError: No module named 'sparseml.yolov8'`
I have tried installing sparseml , pip install -e . ,  sparseml[ultralytics] and ultralytics=8.0.30 but i still face the same error

1. OS [Ubuntu 22.04]:
2. Python version [3.10.0]:
3. sparseml version [1.4.0]:
4. ML framework [torch 1.12.1]:
6.  CUDA version:11.6.0
 I can't install deepsparse either. could that be the issue?

**To Reproduce**
You can create a new conda env with python 3.10.0 and torch 1.12.1 with cudatoolkit 11.6

Any help is appreciated.

**Comment by SuroshAhmadZobair** [comment]
Update:
Until this is fixed, anyone who is blocked can change the imports in train.py and trainers.py  to : 
`from trainers import SparseYOLO
`
Just change sparseml.yolov8.* to trainers and you should be good to go.

**Comment by corey-nm** [comment]
Hey thanks for raising this! Can you post the full stack trace of the module not found error?

ultralytics support is not in sparseml 1.4, so an install through pypi (`pip install sparseml[ultralytics]`) won't work.

However if you do a git clone and pip install from that, it should be.

This works for me:
```bash
> pip uninstall sparseml sparseml-nightly
> git clone https://github.com/neuralmagic/sparseml.git
> pip install ./sparseml[ultralytics]
> sparseml.ultralytics.train --help
```

What errors do you get with the above?

**Comment by corey-nm** [comment]
Ah looks like 1.5 is on nightly now, so you could also install sparseml-nightly from pypi:
```bash
pip install sparseml-nightly[ultralytics]
```
