### ISSUE TITLE
Error while loading the ported onnx model in opencv

### ISSUE THREAD

**Issue by shubham-mishra-verificient** [neuralmagic/sparseml#1443]
I'm getting following error while loading ported onnx model in opencv using cv2.dnn.readNet()
**Error:**
OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [ConvInteger@ai.onnx]:(onnx_node!Conv_178_quant) parse error: OpenCV(4.6.0) d:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layer_internals.hpp:110: error: (-2:Unspecified error) Can't create layer "onnx_node!Conv_178_quant" of type "ConvInteger" in function 'cv::dnn::dnn4_v20220524::detail::LayerData::getLayerInstance'
> 

**Environment**
Include all relevant environment information:
1.windows 10:
2. Python version 3.8.8:
3. Opencv Version: 4.6.0

**Comment by bfineran** [comment]
Hi @shubham-mishra-verificient where are you trying to load this model into? It looks like `handleNode` may be a custom operator from cv2 that may not be supported by other ONNX utilities.

**Comment by shubham-mishra-verificient** [comment]
Hi @bfineran , I am trying to perform inference using ported onnx model in jupyter notebook using opencv cv2.dnn.readNet().
I used following command to port the model"
sparseml.yolov5.export_onnx \
  --weights last.pt \
  --dynamic

**Comment by bfineran** [comment]
It looks like `cv2.dnn.readNet` may not support ONNX `ConvInteger` nodes - if you are deploying on CPUs the model should work with `deepsparse` (`pipeline = Pipeline.create(task="yolo", model_path=...)`)

**Comment by jeanniefinks** [comment]
Hi @shubham-mishra-verificient 
As it's been some time with no further comments @JueXiuHuang , we are going to go ahead and close this issue. If you would like to continue the conversation, please re-open the issue.
Thank you!
Jeannie / Neural Magic
