### ISSUE TITLE
Would SparseML support YoloV5 segmentation soon or at all ?

### ISSUE THREAD

**Issue by thusinh1969** [neuralmagic/sparseml#1462]
**Is your feature request related to a problem? Please describe.**
I am amazed with SparseML but it only support hand full of model like classification Keras, object detection Yolo etc.

**Describe the solution you'd like**
I would like to have SparseML support other model likes Instance Segmentation YoloV5 or TFlite Maker or other Segmentation/Semantic Segmentation frameworks

**Describe alternatives you've considered**
None

**Additional context**
I use a bunch of models together like prediction, object detection, segmentation for the research of selecting good Orange/Chili in Vietnam :)

Thank you.
Steve

**Comment by bfineran** [comment]
Hi @thusinh1969 we don't have official support for yolov5 instance segmentation, however we do have support for yolov8 segmentation.  Take a look here and let me know your thoughts: https://github.com/neuralmagic/sparseml/tree/main/src/sparseml/yolov8

**Comment by flyzxm5177** [comment]
> Hi @thusinh1969 we don't have official support for yolov5 instance segmentation, however we do have support for yolov8 segmentation. Take a look here and let me know your thoughts: https://github.com/neuralmagic/sparseml/tree/main/src/sparseml/yolov8

There is a problem:
`pip install sparseml[ultralytics]`
![image](https://user-images.githubusercontent.com/36351639/229273881-c48e7ec7-4233-4c68-a794-fa30dba3f7b5.png)

`sparseml.ultralytics.train --help`
`bash: sparseml.ultralytics.train: command not found...`

**Comment by bfineran** [comment]
Hi @flyzxm5177 can you try using `sparseml-nightly[ultralytics]` instead?  yolov8 support is on our 1.5 release (currently in nightly)

**Comment by jeanniefinks** [comment]
Hello @flyzxm5177 
As it's been some time with no further comments, we are going to go ahead and close this issue. If you would like to continue the conversation, please re-open the issue.
Thank you!
Jeannie @ Neural Magic
