### ISSUE TITLE
QuestionAnswering Squad-v1 dataset preprocess feature 10784 vs 10833

### ISSUE THREAD

**Issue by xueshengke** [neuralmagic/sparseml#1464]
I ran this repository to evaluate Squad-v1 dataset on Bert-base model, which found the squad-v1 dataset 10570 examples were preprocessed to 10784 features. However, I ran [DeepLearningExamples](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT) Bert eval example and found the squad-v1 dataset 10570 examples were preprocessed to 10833 features. This will lead to minor difference on exact_match and F1 score. I wonder what is the difference between two repos making preproccessing yield different number of features?

This is the log from sparseml:
> [INFO|trainer.py:2966] 2023-03-16 11:29:00,723 >> ***** Running Evaluation *****
[INFO|trainer.py:2968] 2023-03-16 11:29:00,723 >>   Num examples = 10784
[INFO|trainer.py:2971] 2023-03-16 11:29:00,724 >>   Batch size = 256
  0%|          | 0/43 [00:00<?, ?it/s]
  5%|▍         | 2/43 [00:00<00:13,  2.97it/s]
  7%|▋         | 3/43 [00:01<00:18,  2.11it/s]
   ...
 98%|█████████▊| 42/43 [00:28<00:00,  1.47it/s]
100%|██████████| 43/43 [00:28<00:00,  1.95it/s]2023-03-16 11:29:41 
2023-03-16 11:29:53 sparseml.transformers.sparsification.question_answering INFO     Post-processing **10570** example predictions split into **10784** features.
***** eval metrics *****
  eval_exact_match = 80.9082
  eval_f1          = 88.2275
  eval_samples     =   10784

This is the log from [DeepLearningExamples](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT):

> DLL 2023-03-21 08:17:38.458334 - PARAMETER infer_start : True 
DLL 2023-03-21 08:17:38.458385 - PARAMETER eval_samples : **10570** 
DLL 2023-03-21 08:17:38.458418 - PARAMETER eval_features : **10833** 
DLL 2023-03-21 08:17:38.458451 - PARAMETER predict_batch_size : 64 
DLL 2023-03-21 08:17:39.075097 - PARAMETER eval_start : True 
Evaluating:   0%|          | 0/170 [00:00<?, ?it/s]DLL 2023-03-21 08:17:39.078966 - PARAMETER sample_number : 0 
Evaluating:   0%|          | 0/170 [00:20<?, ?it/s]
Evaluating:  25%|██▍       | 42/170 [00:20<01:01,  2.10it/s]
...
Evaluating:  96%|█████████▌| 163/170 [01:18<00:03,  2.10it/s]
Evaluating: 100%|██████████| 170/170 [01:21<00:00,  2.10it/s]
DLL 2023-03-21 08:19:00.124428 -  Elapsed time : 0 h 1 m 21.050 s 
DLL 2023-03-21 08:20:10.984030 -  saving answers to : ['results/SQuAD/predictions.json', 'results/SQuAD/nbest_predictions.json'] 
DLL 2023-03-21 08:20:16.691307 -  exact_match : 81.466 None F1 : 88.687 None

Anyone can solve this issue? Thank you very much.

**Comment by bfineran** [comment]
Hi @xueshengke what are the sequence lengths and doc strides used for both of your evaluation runs? The number of features depends on how the question/context pairs may be strided after they go over the sequence length.  Differences in how this strategy is implemented may also lead to this.

**Comment by xueshengke** [comment]
> Hi @xueshengke what are the sequence lengths and doc strides used for both of your evaluation runs? The number of features depends on how the question/context pairs may be strided after they go over the sequence length. Differences in how this strategy is implemented may also lead to this.

The max sequence length is 384 and doc stride is 128 for both cases.

**Comment by bfineran** [comment]
Since the seq length and doc strides are the same and we defer to the HF base implementation, I don't think we can say much more on what could be different in the NVIDIA implementation.  Having a different number of samples will lead to a slightly different accuracy result as noted before.

**Comment by jeanniefinks** [comment]
Hello @xueshengke 
As it's been some time with no further comments, we are going to go ahead and close this issue. If you would like to continue the conversation, please go ahead and re-open the issue.
Thank you!
Jeannie @ Neural Magic
