### ISSUE TITLE
torch 2.0 support

### ISSUE THREAD

**Issue by lminer** [neuralmagic/sparseml#1504]
Just wondering if you have torch 2.0 support planned anytime soon.

**Comment by bfineran** [comment]
Hi @lminer torch 2.0 support isn't planned yet due to the current lack of support for hooks (see https://pytorch.org/get-started/pytorch-2.0/#hooks 4/3/23). We use hooks to build our training aware sparsification implementations so are currently planning on re-evaluating once hooks are added back

**Comment by bfineran** [comment]
Hi @cbalint13 this looks like a great result! Thank you for sharing. What recipe were you running? And were you able to verify that the final model was sparsified? Torch 2.0 is listed as backwards compatible with 1.X so it is a good signal that none of our most used torch pathways were broken.

Any chance you used the new `torch.compile` feature which seems to be the main value add? I would guess that things break there.

Will have someone on the team investigate further as well.

**Comment by cbalint13** [comment]
> 


Hi @bfineran,

> Hi @cbalint13 this looks like a great result! Thank you for sharing. 
>What recipe were you running? 

* I run [default one demo](https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/yolov8/README.md) but with ```params: __ALL_PRUNABLE__``` .

>And were you able to verify that the final model was sparsified? 

* Using onnx model via TVM, see [sparse demo](https://tvm.apache.org/docs/how_to/deploy_models/deploy_sparse.html) ends up in real BSR
* There is a  ```relay.transform.DenseToSparse``` strep, after it is easy to check the "sparseness"
* Further TVM finds ways to tune/optimize all the operators and compile to target's final runtime
* Yolov8 looks a hard nut to sparsify, currently unable to go beyond 0.2 sparse levels

>Torch 2.0 is listed as backwards compatible with 1.X so it is a good signal that none of our most used torch pathways were broken.

> Any chance you used the new `torch.compile` feature which seems to be the main value add? I would guess that things break there.

* Not sure what you asked here regarding ````torch.compile```
* I export the model to onnx (works well) and compile/tune it within TVM

My current goal is not the sparseness part (yes, that also would be nice) but primary target is the quantization part.

> 
> Will have someone on the team investigate further as well.

Would be great if pytorch 2.x is supported.

Thank you @bfineran  !

**Comment by naveen715** [comment]
Hi @cbalint13 ,
> * I run [default one demo](https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/yolov8/README.md) but with `params: __ALL_PRUNABLE__` .
I was trying to run the same but wasn't able to do so I ran the command 
!sparseml.ultralytics.train --task=detect --data=/content/drive/MyDrive/YOLOV8/datasets/drones-8/data.yaml --batch 4 --epochs 50 --recipe yolov8-pq.yaml
But it returned a error 
FileNotFoundError: [Errno 2] No such file or directory: 'yolov8-pq.yaml'
I even ran it with the recipe you used still the same error how to add recipe while training with yolov8 
and what are the methods to decrease inference time for yolov8

**Comment by cbalint13** [comment]
@naveen715 

> Hi @cbalint13 ,
> 
> > * I run [default one demo](https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/yolov8/README.md) but with `params: __ALL_PRUNABLE__` .
> 
> I was trying to run the same but wasn't able to do so I ran the command !sparseml.ultralytics.train --task=detect --data=/content/drive/MyDrive/YOLOV8/datasets/drones-8/data.yaml --batch 4 --epochs 50 --recipe yolov8-pq.yaml But it returned a error FileNotFoundError: [Errno 2] No such file or directory: 'yolov8-pq.yaml' 

* As mentioned and described in [yolov8/README.md](https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/yolov8/README.md), you can try that default sample as a baseline:

```
$ cat yolov8-pq.yaml
version: 1.1.0

training_modifiers:
  - !EpochRangeModifier
    start_epoch: 0
    end_epoch: 15

pruning_modifiers:
  - !GMPruningModifier
    init_sparsity: 0.05
    final_sparsity: 0.10
    start_epoch: 5.0
    end_epoch: 10.0
    update_frequency: 1.0
    params: __ALL_PRUNABLE__

quantization_modifiers:
  - !QuantizationModifier
    start_epoch: 11.0
    freeze_bn_stats_epoch: 12.0
    disable_quantization_observer_epoch: 13.0
    ignore: ["Upsample", "Concat", "SiLU"]
```

>I even ran it with the recipe you used still the same error how to add recipe while training with yolov8 and what are the >methods to decrease inference time for yolov8

* Also based on that sample, you can try your own variation that sparsify even more deeply.

I am interested in quantization step only, which worked out well (but the QAT here is not PoT aware, not yet).

**Comment by naveen715** [comment]
Soo now after training how to validate the model 
i was trying !yolo task=detect mode=predict conf=0.25 source='/content/drive/MyDrive/YOLOV8/testnew.mp4' model=/content/drive/MyDrive/Sparse/runs/detect/train7/weights/best.pt but this command threw an error

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/cfg/__init__.py", line 364, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/nn/tasks.py", line 419, in attempt_load_one_weight
    model = (ckpt.get('ema') or ckpt['model']).to(device).int()  # FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

how to resolve this or how to use our trained model

**Comment by bfineran** [comment]
Hi @naveen715 it looks like you are trying to load a sparsified yolo checkpoint (saved as a dictionary) with the base ultralytics loading flow (expects a pickled model), what pathway are you running this through? If it's not one of our already supported pathway's we'll need to add in support to get the model unwrapped from a dictionary

**Comment by jeanniefinks** [comment]
Hi @naveen715
Following up here on our question; thank you so much!
Jeannie / Neural Magic

**Comment by mgoin** [comment]
Feel free to open this back up if needed, it seems to be left dangling

**Comment by danielemaasit** [comment]
@mgoin &  @jeanniefinks I ran into the same error when loading a sparsified checkpoint using YOLO(sparsified_checkpoint.pt). ``model = (ckpt.get('ema') or ckpt['model']).to(device).int() # FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'to'``.

I see you asked @naveen715 `what pathway are you running this through? If it's not one of our already supported pathway's we'll need to add in support to get the model unwrapped from a dictionary`. What does this mean i.e. pathway?

**Comment by mgoin** [comment]
Hi @danielemaasit , like Ben said for the previous user, it looks like you are trying to load a sparse yolo checkpoint with the base ultralytics loading flow, which isn't a supported flow through our examples (what we mean by "pathway"). 
Our usual flow involves[ exporting that checkpoint to ONNX ](https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics-yolov5#export-to-onnx)and running it with [DeepSparse for inference](https://github.com/neuralmagic/deepsparse/blob/main/docs/use-cases/cv/object-detection-yolov5.md). DeepSparse integrates with Ultralytics to take care of the complexity and give the best performance! Have you taken a chance to try that first?

**Comment by jeanniefinks** [comment]
Hello @danielemaasit 
Some time has passed between our last comment and hearing back. I'd like to go ahead and close out this thread. But if you would like to continue the conversation, please re-open this issue. Thank you so much!
Jeannie / Neural Magic
