### ISSUE TITLE
[Quantization] PoT (power-of two) scaling awareness feature

### ISSUE THREAD

**Issue by cbalint13** [neuralmagic/sparseml#1519]
Hi folks,

As continued discussion at #1504 would ask few questions on this feature before proceeding to some contribution.

### Intro

Regarding quantization currently SparseML lacks any kind of PoT (power-of-two) awareness.
PoT would enable pure-integer networks,  allowing NPU/FPGA kind of accelerators that lacks floating-point.

Actual state:
  1. Current quantization (QAT mode) is basically done inserting ```QuantizeLinear``` (float scaling then to-integer-cast)
  2. Current ```QuantizeLinear``` cannot be replaced by ```BitShift``` due to scaling factors not being PoT aware: [discuss here](https://discuss.pytorch.org/t/how-to-set-quantization-aware-training-scaling-factors/65872/7)

Note: ```BitShift``` is a mul (left) or div (right) on integers but only with power's of two, super efficient on any hardware.

### Possibilities

Now, there would be some opportunity for PoT aware QAT and final graph export (ONNX) to pure integers:

  * **A** By fixing/revive the broken pytorch experimental [APoT functions](https://github.com/pytorch/pytorch/tree/master/torch/ao/quantization/experimental) 
  * **B** Or by simply clamping ```y_scale``` to *1/2^N* or a composed *sum(1/2^{N1,N2,Nx})* series (with x=*depth-limit*).

**A** -> would be elegant, it learns the PoT scale, would end in a single  ```BitShift``` but requires PR and fixes to pytorch.
**B** -> would (currently testing) end up in multiple (by depth-limit = 2 or 3) ```BitShift``` plus final ```Add```  for all of them.

After, 

SparseML could export the graph (ONNX) with replaced ```QuantizeLinear``` -> ```BitShift``` . 
Same would go for the ```Dequantization``` and later for those scalar ```Mul``` (back-conversions).

TVM as example, a post compiler/tuner, finds ways to fuse ```BitShift``` into subseqent ```Conv``` when HW is not VNNI / AMX.

### Questions

Could help with a initial attempt to implement, but:
   * A: clamp ```y_scale``` to sum(1/2^{N1,N2,Nx}), x=depth-limit) in pytorch's [observer.py](https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/observer.py#L326-L370) as a PR ?
   * B: or may be this ```y_scale``` be clamped and manipulated **only** from sparseml side (with some hooks) ?
 
Currently I am testing A (on pytorch side) but perhaps we could end without touching pytorch upstream at all.
Either A or B, at export step, ```QuantizeLinear``` can be mangled to ```BitShift``` by PoT aware ```y_scale``` (on sparseml side).

---

What do you think on such PoT awareness ?

Thanks,
~Cristian.

**Comment by cbalint13** [comment]
I am closing this since currently I found independent ways for QAT / APoT.

**Comment by mgoin** [comment]
This is a cool idea! I've been interested in exploring how sub-8-bit precision can be represented in ONNX so this could be helpful towards that goal

**Comment by cbalint13** [comment]
> This is a cool idea! I've been interested in exploring how sub-8-bit precision can be represented in ONNX so this could be helpful towards that goal

@mgoin,

* It is not about sub-8-bit, it is still u/int8 (keeping actual ```ConvInteger```) but **without** any ```floating-point``` scaling at all, so all ```De/QuantizeLinear``` and their post ```Mul``` (with one scalar) counterparts can be dropped completely away in favour/substitute of a very cheap ```BitShift``` operator.

**Comment by shoskensMagics** [comment]
> I am closing this since currently I found independent ways for QAT / APoT.

@cbalint13 

Can you elaborate on your choice of tools to get the job done?
Doing something similar; PoT aware QAT > TVM > NPU only allowing these bit shift operations instead of quant/dequant.

**Comment by cbalint13** [comment]
> > I am closing this since currently I found independent ways for QAT / APoT.
> 
> @cbalint13
> 
> Can you elaborate on your choice of tools to get the job done? Doing something similar; PoT aware QAT > TVM > NPU only allowing these bit shift operations instead of quant/dequant.

* https://github.com/Xilinx/brevitas
* https://github.com/quic/aimet
