### ISSUE TITLE
No recipe found

### ISSUE THREAD

**Issue by naveen715** [neuralmagic/sparseml#1530]
I was not able to apply any recipe
!sparseml.ultralytics.train --task=detect --data=/content/drive/MyDrive/YOLOV8/datasets/drones-8/data.yaml --batch 4 --epochs 50 --recipe yolov8-pq.yaml
FileNotFoundError: [Errno 2] No such file or directory: 'yolov8-pq.yaml'
How to use recipe with Yolov8  and how to sparsify my model please provide me more information about weather sparcifying and applying recipe will reduce inference time .

**Comment by mgoin** [comment]
Hi @naveen715 , could you try providing an absolute filepath to 'yolov8-pq.yaml' like you did for the 'data.yaml`?

**Comment by jeanniefinks** [comment]
Hi @naveen715
Following up here on our question; thank you so much!
Jeannie / Neural Magic
