### ISSUE TITLE
Colab pip install incompatibilities | Sparseml cant use yolov5 integration 

### ISSUE THREAD

**Issue by MrShirker** [neuralmagic/sparseml#1587]
Hello i'm a newbie to all of this so maybe im doing something wrong. Thanks in advance.

I've been using yolov5 training and detection for a while in a college project, and now i discovered neuralmagic integration with yolov5. I dont have access to a gpu so this sounded great. That said i use google colab, and after i clone the sparseml repository, the deepsparse one or even te neuralmagic/yolov5 fork into colab; and i try to pip install the requirements or launch the setup.py 

I've watching all yolov5 related videos from your youtube channel, but i cant seem to replicate your results.

I tried a lot of things so i'm gonna add more than one issue in this post. Sorry if thats inconvenient. 

______________________________________________________________________________________________________________________________________________

1) Here is an example of the error i encounter, in colab:

> !git clone https://github.com/neuralmagic/sparseml

> !pip install sparseml[torchvision]

and here is the output:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> arviz 0.15.1 requires setuptools>=60.0.0, but you have setuptools 59.5.0 which is incompatible.
> cvxpy 1.3.1 requires setuptools>65.5.1, but you have setuptools 59.5.0 which is incompatible.
> google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> google-cloud-bigquery 3.9.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> google-cloud-bigquery-storage 2.19.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> google-cloud-datastore 2.15.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> google-cloud-firestore 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> google-cloud-language 2.9.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> google-cloud-translate 3.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> googleapis-common-protos 1.59.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
> tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.21.6 which is incompatible.
> tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.1 which is incompatible.
> tensorflow-metadata 1.13.1 requires protobuf<5,>=3.20.3, but you have protobuf 3.20.1 which is incompatible.
> torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.12.0 which is incompatible.
> torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.12.0 which is incompatible.
> torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.12.0 which is incompatible.
> Successfully installed GPUtil-1.4.0 click-8.0.4 gputils-1.0.6 jedi-0.18.2 jupyter-1.0.0 merge-args-0.1.5 numpy-1.21.6 onnx-1.12.0 protobuf-3.20.1 qtconsole-5.4.3 qtpy-2.3.1 setuptools-59.5.0 sparseml-1.4.4 sparsezoo-1.4.0 toposort-1.10 torch-1.12.0 torchvision-0.13.0
> WARNING: The following packages were previously imported in this runtime:
>   [_distutils_hack,google,numpy,pkg_resources,setuptools]
> You must restart the runtime in order to use newly installed versions.
> 

In the videos i've seen , 10 months old, thats how you do it, but i cant get it to work. I think there is a version conflict in this modules [_distutils_hack,google,numpy,pkg_resources,setuptools]

______________________________________________________________________________________________________________________________________________

2) In my laptop, no gpu, i've tried to use the train.py inside the neuralmagic/yolov5 repository like this:

> python train.py --cfg models/yolov5s.yaml --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn --data Final_corregido.yaml --hyp ../yolov5-deepsparse-blogpost/yolov5-train/data/hyps/hyp.scratch.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn --img 640 --batch-size 16 --epochs 5 --save-period 15 --optimizer SGD --project ../resultados --name yolov5s-sgd-pruned 

And 10 hours later i thought it work, but now i have a .pt file that i cant load or export to onnx, with the basic ultralytics/yolov5 scripts,  so tried to install sparseml[torchvision] on my computer, no gpu, in a venv:

> pip install sparseml[torchvision]

But when i try to use the comands, i get this error:

> (env) C:\Users\shirk\IA\Sparseml>sparseml.yolov5.export_onnx --weights small_pruned.pt
> C:\Users\shirk\IA\Sparseml\env\lib\site-packages\torchvision\models\detection\anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
>   device: torch.device = torch.device("cpu"),
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\shirk\IA\Sparseml\env\Scripts\sparseml.yolov5.export_onnx.exe\__main__.py", line 4, in <module>
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\yolov5\scripts.py", line 16, in <module>
>     from sparseml.pytorch.utils.distributed import record
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\__init__.py", line 51, in <module>
>     from .framework import detect_framework, framework_info, is_supported
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\framework\__init__.py", line 24, in <module>
>     from .info import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\framework\info.py", line 26, in <module>
>     from sparseml.pytorch.sparsification import sparsification_info
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\sparsification\__init__.py", line 24, in <module>
>     from .distillation import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\sparsification\distillation\__init__.py", line 17, in <module>
>     from .modifier_distillation import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\sparsification\distillation\modifier_distillation.py", line 24, in <module>
>     from sparseml.pytorch.sparsification.distillation.modifier_distillation_base import (
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\sparsification\distillation\modifier_distillation_base.py", line 30, in <module>
>     from sparseml.pytorch.sparsification.modifier import (
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\sparsification\modifier.py", line 36, in <module>
>     from sparseml.pytorch.utils import LOGGING_LEVELS, BaseLogger, LoggerManager
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\utils\__init__.py", line 24, in <module>
>     from .exporter import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\pytorch\utils\exporter.py", line 37, in <module>
>     from sparseml.onnx.utils import ONNXGraph
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\__init__.py", line 22, in <module>
>     from .benchmark import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\benchmark\__init__.py", line 22, in <module>
>     from .info import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\benchmark\info.py", line 28, in <module>
>     from sparseml.onnx.framework import framework_info as get_framework_info
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\framework\__init__.py", line 24, in <module>
>     from .info import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\framework\info.py", line 26, in <module>
>     from sparseml.onnx.sparsification import sparsification_info
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\sparsification\__init__.py", line 24, in <module>
>     from .analyzer import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\sparsification\analyzer.py", line 26, in <module>
>     from sparseml.onnx.utils import DataLoader, DeepSparseAnalyzeModelRunner, ONNXGraph
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\utils\__init__.py", line 25, in <module>
>     from .loss import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\sparseml\onnx\utils\loss.py", line 16, in <module>
>     from scipy.stats import entropy
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\scipy\stats\__init__.py", line 485, in <module>
>     from ._stats_py import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\scipy\stats\_stats_py.py", line 39, in <module>
>     from scipy.spatial.distance import cdist
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\scipy\spatial\__init__.py", line 105, in <module>
>     from ._kdtree import *
>   File "C:\Users\shirk\IA\Sparseml\env\lib\site-packages\scipy\spatial\_kdtree.py", line 4, in <module>
>     from ._ckdtree import cKDTree, cKDTreeNode
>   File "_ckdtree.pyx", line 1, in init scipy.spatial._ckdtree
> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

______________________________________________________________________________________________________________________________________________

3) When i try to load the small_pruned.pt with:

> model = torch.hub.load('ultralytics/yolov5', 'custom', path='./models/small_pruned.pt', force_reload=True)

i get this error:

> Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\shirk/.cache\torch\hub\master.zip
> YOLOv5  2023-5-28 Python-3.10.11 torch-2.0.0+cpu CPU
> 
> Traceback (most recent call last):
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 49, in _create
>     model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 344, in __init__
>     model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 80, in attempt_load
>     ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
> AttributeError: 'collections.OrderedDict' object has no attribute 'to'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 60, in _create
>     model = attempt_load(path, device=device, fuse=False)  # arbitrary model
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 80, in attempt_load
>     ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
> AttributeError: 'collections.OrderedDict' object has no attribute 'to'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\shirk\OneDrive\Documentos\Master\Proyecto_II\GitHub\TP2\Coche\main.py", line 178, in <module>
>     modelo_clasificador = torch.hub.load('ultralytics/yolov5', 'custom', path='./modelos/small_pruned.pt', force_reload=True)
>   File "C:\Users\shirk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\hub.py", line 558, in load
>     model = _load_local(repo_or_dir, model, *args, **kwargs)
>   File "C:\Users\shirk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\hub.py", line 587, in _load_local
>     model = entry(*args, **kwargs)
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
>     return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
>   File "C:\Users\shirk/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 78, in _create
>     raise Exception(s) from e
> Exception: 'collections.OrderedDict' object has no attribute 'to'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help

**Comment by MrShirker** [comment]
I found a solution to the colab problem. You can create virtual enviroments inside colab to avoid incompatibilities:

> !pip3 install virtualenv
> !virtualenv theanoEnv

the you:

> !source /content/theanoEnv/bin/activate; pip3 install theano

And you can install sparseml without the previus issue:

> !source /content/theanoEnv/bin/activate; pip3 install sparseml[torchvision]; pip3 list

now im using this command to prune my model:

> !source /content/theanoEnv/bin/activate; sparseml.yolov5.train \
>   --cfg yolov5/models_v5.0/yolov5s.yaml --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn \
>   --data Final_corregido.yaml --hyp yolov5/data/hyps/hyp.finetune.yaml \
>   --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn \
>   --img 640 --batch-size 64 --epochs 5 --save-period 15 --optimizer SGD \
>   --project "/content/drive/MyDrive/IA/Pesos_yoloV5/Final_corregido" --name "Small_pruned"

This find is worth 2 full days of banging my head aginst the keybord.............

**Comment by MrShirker** [comment]
I will be back if im not able to use the .pt that comes out of this to export it or to use it directly. so dont close this please.

**Comment by MrShirker** [comment]
Now i'm trying to validate the model like this: 

> !source /content/theanoEnv/bin/activate; sparseml.yolov5.val \
>                 --task test \
>                 --data Final_corregido.yaml \
>                 --weights ../drive/MyDrive/IA/Pesos_yoloV5/Final_corregido/Small_pruned_quant_Blog/weights/best.pt \
>                 --conf-thres 0.40 \
>                 --project ../drive/MyDrive/IA/Pesos_yoloV5/Final_corregido/Metricas --name Small_pruned_quant_Blog

And this is the output:

> /bin/bash: sparseml.yolov5.val: command not found

But im able to use sparseml.yolov5.train and sparseml.yolov5.export_onnx without problems.

**Comment by bfineran** [comment]
hi @MrShirker the correct command should be `sparseml.yolov5.validation`.  If you saw `val` somewhere in our documentation, we can get that updated.

What metrics are you getting back?

**Comment by jeanniefinks** [comment]
Hello @MrShirker 
Just circling back to see if you are able to supply any metrics to continue the conversation? Thank you!
Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hi @MrShirker 
Some time has passed between our last comment and hearing back. I'd like to go ahead and close out this thread. But if you would like to continue the conversation, please re-open this issue. Thank you so much!
Jeannie / Neural Magic
