### ISSUE TITLE
When using Sparsify UI, is anything uploaded elsewhere?

### ISSUE THREAD

**Issue by IdoZach** [neuralmagic/sparseml#160]
Hi, 
When running the Sparsify UI which uses SparseML and other repositories, is any model data or other information sent to a remote Neural Magic or other server? or is everything done locally on my own machine? 
I couldn't find an answer in the docs.
Thanks.

**Comment by markurtz** [comment]
Hi @IdoZach, thanks for the question! Privacy is definitely something we're very conscious of for anyone using these tools, so everything stays local to your machine. 

If you'd like to verify, you can track the network traffic while sparsify is running in the chrome developer tools to see that all traffic is going to your local machine where the sparsify server is running from. Additionally, you can shut down all outbound and inbound ports on the server other than 5543 for access from the browser and it will run the same.

We'll be sure to update the Sparsify docs to make this clearer.

**Comment by jeanniefinks** [comment]
As this issue has been opened for some time and there are no further comments or questions, we'll close this issue out. We have a roadmap item to overhaul our Sparsify docs and have ear-marked this comment for inclusion into those enhanced docs. Thanks again @IdoZach!

Jeannie / Neural Magic
