### ISSUE TITLE
[Required for MPT models] Increase ONNX opset to 14

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#1632]
Exporting MosaicML MPT models fails because they require opset 14, and we currently support 13 https://github.com/neuralmagic/sparseml/blob/c3612a19b16a3d60493ff5447c5c860c16e172df/src/sparseml/pytorch/opset.py#L25

I haven't checked what implications this has on other models, but increasing 13 to 14 in the line above allows us to export MPT models.

@bfineran @mgoin

**Comment by bfineran** [comment]
Hi @eldarkurtic - right now we can't add default opset support for 14 as the deepsparse engine does not fully support it yet. In the meantime for MPT, can you do one off exports in opset 14? 
Surprised we don't have an opset arg in `sparseml.transformers.export_onnx` we can get that added in if that helps

**Comment by mgoin** [comment]
Should be straightforward to ensure full support https://github.com/onnx/onnx/releases/tag/v1.9.0

+1 on adding an opset arg, very useful for debugging

**Comment by bfineran** [comment]
Updating here that MPT support in sparseml/deepsparse will be available in the next release

**Comment by jeanniefinks** [comment]
Closing out this issue as Opset 14 officially was released with 1.6 per https://github.com/neuralmagic/sparseml/releases/tag/v1.6.0
