### ISSUE TITLE
Search for models in the sparsezoo using architecture_name

### ISSUE THREAD

**Issue by hello-fri-end** [neuralmagic/sparseml#1712]
The `sparsezoo.search_models` has two required arguments - `domain` and `subdomain`. Is there a way to search the `sparsezoo` for models using just the `architecture` name?

**Comment by NMfitz** [comment]
Hi @hello-fri-end - you are referring to the SparseZoo CLI tool, not the [website](https://sparsezoo.neuralmagic.com/), correct? If yes, FYI @bfineran

**Comment by hello-fri-end** [comment]
> Hi @hello-fri-end - you are referring to the SparseZoo CLI tool, not the [website](https://sparsezoo.neuralmagic.com/), correct? If yes, FYI @bfineran

I was referring to the python API 😅

**Comment by NMfitz** [comment]
thanks for the clarification! I work on the GUI/UX SparseZoo -  Ben can assist on the API

**Comment by bfineran** [comment]
Hi @hello-fri-end thanks for the question - domain and subdomain are required for the search API. as @NMfitz pointed out for architecture only search the website may be useful.

**Comment by hello-fri-end** [comment]
> Hi @hello-fri-end thanks for the question - domain and subdomain are required for the search API. as @NMfitz pointed out for architecture only search the website may be useful.

Thanks for the answers @NMfitz @bfineran. Maybe it's worth adding this feature though - just a suggestion :smile:

**Comment by NMfitz** [comment]
Thank you @hello-fri-end for your suggestion - I've put it on our product requests board.

**Comment by NMfitz** [comment]
Request noted and documented in the product request backlog
