### ISSUE TITLE
Got error on YOLOv8n `sparseml.ultralytics.train` train starting

### ISSUE THREAD

**Issue by dmytro587** [neuralmagic/sparseml#1754]
**Describe the bug** 
An example from the [yolo tutorial](https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov8/tutorials/sparse-transfer-learning.md) are failed:
```
sparseml.ultralytics.train \
  --model "zoo:cv/detection/yolov8-n/pytorch/ultralytics/coco/pruned49-none" \
  --recipe "zoo:cv/detection/yolov8-n/pytorch/ultralytics/voc/pruned49_quant-none" \
  --data "coco128.yaml" \
  --batch 8
```

**Expected behavior**
I expecting successful training

**Environment**
Include all relevant environment information:
1. OS: Ubuntu 22.04.2 LTS
2. Python version: 3.10.12
3. SparseML version: 1.5.4
4. ML framework version (torch): 1.13.1 (also Google Colab has pre-installed installed tensorflow==2.13.0)
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]: sparsezoo==1.5.2, numpy==1.21.6, onnx==1.12.0
6. Other relevant environment information [e.g. hardware, CUDA version]: CPU

**To Reproduce**
Run two blocks to reproduce https://colab.research.google.com/drive/1747JjxD8vf_dplYaxVQwdhdzyFPdCgKt?hl=ru#scrollTo=6SMdx7pg91rY

**Errors**
<img width="810" alt="Screenshot 2023-10-09 at 18 09 00" src="https://github.com/neuralmagic/sparseml/assets/55716932/600c87fe-20b6-4708-bfb8-c0a8372062ab">

**Comment by esquire900** [comment]
```
pip install numpy opencv-contrib-python --upgrade
```
Solved it for me

(to versions numpy-1.25.2 opencv-contrib-python-4.8.1.78)

**Comment by dmytro587** [comment]
> ```
> pip install numpy opencv-contrib-python --upgrade
> ```
> 
> Solved it for me
> 
> (to versions numpy-1.25.2 opencv-contrib-python-4.8.1.78)

Solved for me too, thank you ❤️
