### ISSUE TITLE
My own model

### ISSUE THREAD

**Issue by grpinto** [neuralmagic/sparseml#1765]
Hello,

Is it possible for me to optimize my own develop model using your code with no change or you currently do not support this sort of feature, it is not clear to. Thanks for the attention.

Congrats on the great repo

**Comment by rgreenberg1** [comment]
Yes, it's certainly possible. It would be great if you could tell me a bit more about the type of model/what you are trying to accomplish and what tradeoffs would be acceptable. 

Please join our [Slack Community](https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-1xkdlzwv9-2rvS6yQcCs7VDNUcWxctnw) and dm me @Rob Greenberg
