### ISSUE TITLE
PyTorch 2.1.0 and Lightning 2.1.0 Support: AssertionError on `assert self._strategy is not None`

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/sparseml#1815]
**Describe the bug**

I am trying to update sparseml and lightning so that they can both work together on torch 2.1.0.

I need torch 2.1.0 as I can't export Dinov2 in an onnx format under torch 2.0.0 because the the flash attention modules.

What I have done already:
- [SparseML Callback](https://github.com/clementpoiret/lightning-bolts/tree/fix/sparseml)
  - fixed mixed imports (the original callback calls `pytorch_lightning`, but the way to go now is to use `lightning.pytorch`. Mixing the two causes issues.)

- [SparseML](https://github.com/clementpoiret/sparseml/tree/fix/torch_version)
  - Bumped torch max version to 2.1.100

After that, I am able to correctly import and define the objects as in:

```python
import os

import lightning as L
import timm
from pl_bolts.callbacks import SparseMLCallback  # from updated fork
from torch import Tensor, nn, optim, utils
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor


class Model(L.LightningModule):

    def __init__(self):
        super().__init__()
        backbone = timm.create_model("vit_small_patch14_reg4_dinov2.lvd142m",
                                     pretrained=True)
        for param in backbone.parameters():
            param.requires_grad = False

        self.model = nn.Sequential(backbone, nn.Linear(backbone.num_features,
                                                       10))

    def forward(self, x):
        y_hat = self.model(x)
        return y_hat

    def training_step(self, batch, batch_idx):
        x, y = batch

        # Duplicate in channels to match pretrained weights
        x = x.repeat(1, 3, 1, 1)

        # interpolate to 518*518
        x = nn.functional.interpolate(x, size=(518, 518))

        y_hat = self.forward(x)
        loss = nn.functional.cross_entropy(y_hat, y)
        # Logging to TensorBoard (if installed) by default
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


clf = Model()

# setup data
dataset = MNIST(os.getcwd(), download=True, transform=ToTensor())
train_loader = utils.data.DataLoader(dataset)

# train the model
callbacks = [SparseMLCallback(recipe_path='recipe.yaml')]
trainer = L.Trainer(accelerator='gpu',
                    strategy='auto',
                    limit_train_batches=100,
                    max_epochs=2,
                    callbacks=callbacks)
trainer.fit(model=clf, train_dataloaders=train_loader)
```

with the following recipe:

```yaml
version: 0.1.0
modifiers:
    - !EpochRangeModifier
        start_epoch: 0.0
        end_epoch: 64.0

    - !QuantizationModifier
        start_epoch: 0.0
```

Unfortunately, I am getting the following issue: `AssertionError: assert self._strategy is not None`

The assert statement is located here: https://github.com/Lightning-AI/lightning/blob/c524c0b01bba46b7ffb6b0668242d92084cdd44b/src/lightning/pytorch/core/optimizer.py#L150

This happens because of the modification of the optimizer by the `ScheduledModifierManager` by the callback at https://github.com/clementpoiret/lightning-bolts/blob/70cc5f5c3bb9e993d7b96f0f49514ff6bb0bbc98/src/pl_bolts/callbacks/sparseml.py#L52C33-L52C33

Then it goes a bit too deep into SparseML's logic, I believe a new LightningOptimizer is instanciated, but maybe the "strategy" is something new and discarded by the modification of the manager class.

Do you have any clue of what I can update?

**Expected behavior**

A quantization aware training just after `fit()` :)

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Arch Linux
2. Python version [e.g. 3.7]: 3.10
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: commit of the branch I linked earlier
4. ML framework version(s) [e.g. torch 1.7.1]: torch 2.1.0
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]: lightning 2.1.0
6. Other relevant environment information [e.g. hardware, CUDA version]: lightning-bolts of the branch I linked earlier too.

**To Reproduce**

Install the two updated libs from my branches, and run the code snippet I pasted at the beginning.

**Errors**

```
>>> trainer.fit(model=clf, train_dataloaders=train_loader)
You are using a CUDA device ('NVIDIA GeForce RTX 4080') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'hi
gh')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_f
loat32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loading `train_dataloader` to estimate number of stepping batches.
/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have ma
ny workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=23` in the `DataLoader` to improve performance.
2023-11-08 18:30:59 sparseml.core.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/08-11-2023_18.30.59.log

  | Name  | Type       | Params
-------------------------------------
0 | model | Sequential | 22.1 M
-------------------------------------
3.9 K     Trainable params
22.1 M    Non-trainable params
22.1 M    Total params
88.245    Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                    | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1282, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/clementpoiret/micromamba/envs/torch/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py", line 150, in step
    assert self._strategy is not None
AssertionError
```

**Comment by clementpoiret** [comment]
Update on my issue, it seems that the optimizer setter is not triggered by the callback: `https://github.com/Lightning-AI/lightning/blob/618e1c8061753e767e7ae628cf55098b8fa6ad55/src/lightning/pytorch/strategies/strategy.py#L107`

Meaning that the resulting `LightningOptimizer` is not properly initialized by `LightningOptimizer._to_lightning_optimizer`.

One quick hack would be to either modify the already existing object such as:

```python
    def on_fit_start(self, trainer: Trainer,
                     pl_module: LightningModule) -> None:
        if len(trainer.strategy.optimizers) > 1:
            raise MisconfigurationException(
                "SparseML only supports training with one optimizer.")
        optimizer = trainer.strategy.optimizers[0]

        optimizer = self.manager.modify(
            pl_module,
            optimizer,
            steps_per_epoch=trainer.estimated_stepping_batches,
            epoch=0)

        trainer.strategy._optimizers = [optimizer]
        trainer.strategy._lightning_optimizers[0]._optimizer = optimizer
```

What do you think about this possible solution? I'm afraid this would break older versions of pytorch lightnings, as I did not tested on older versions.

**Comment by mgoin** [comment]
Hey @clementpoiret I think the lightning integration isn't heavily used so I wouldn't have concern with backwards compatibility for that interface. My main concern would be with torch 2.1 affecting other flows. It sounds like that upgrade would still be needed for your DINO usecase, correct?

**Comment by clementpoiret** [comment]
Yes, unfortunately I can't export dinov2 in onnx using torch 2.0 as I am getting `torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported.`
This issue has been fixed by the 2.1 update

**Comment by mgoin** [comment]
Hey @clementpoiret we upgrade support to `torch<2.2` on the latest `sparseml-nightly`. Please give it a try and let me know if you need any other assistance

**Comment by clementpoiret** [comment]
Hey @mgoin thanks for the update
I can confirm everything works on my side!

**Comment by clementpoiret** [comment]
Okay @mgoin, I'll correct what I said 😂 my fix of the lightning callback was just (I believe) incorrectly applying the optimizer, thus dismissing the error. Actually, I end up with non sparse models, meaning the optimizer step isn't applied correctly... So I still have the issue with sparseml 1.6.0: the ScheduledModifierManager and the LightningOptimizer config have issues working together. I ended with the same issue as above : self._strategy is none.

**Comment by clementpoiret** [comment]
Okay, I believe it's just a mix of ambiguities here and there, what I said above is weird, I still don't understand why modifying the base optimizer reset lightning's strategy, but setting modifying the optimizer of the `LightningOptimizer` seems to be okay now.

What happened is quite simple: `trainer.estimated_stepping_batches` was incorrect, leading modifiers to be close to never applied, thus `start_epoch` and `end_epoch` being completely off. Manually indicating step_per_epoch fixed the issue and applied all modifiers.

My last weird error is a warning when exporting to ONNX, telling that I should disable constant folding if the training=TrainingMode.PRESERVE or TrainingMode.TRAINING. I don't get how to modify this behavior. I keep having the warning even when setting `export_onnx(..., training=TrainingMode.EVAL)` or setting `model.training = False`.

For the sake of reference, here is the updated SparseMLCallback:

```python
from typing import Any, Optional

import torch
from lightning.pytorch import Callback, LightningModule, Trainer
from lightning.pytorch.utilities.exceptions import MisconfigurationException
from sparseml.pytorch.optim import ScheduledModifierManager
from sparseml.pytorch.utils import ModuleExporter


class SparseMLCallback(Callback):
    """Enables SparseML aware training. Requires a recipe to run during training.

    Args:
        recipe_path: Path to a SparseML compatible yaml recipe.
            More information at https://docs.neuralmagic.com/sparseml/source/recipes.html

    """

    def __init__(self,
                 recipe_path: str,
                 steps_per_epoch: Optional[int] = None) -> None:
        self.manager = ScheduledModifierManager.from_yaml(recipe_path)
        self.steps_per_epoch = steps_per_epoch

    def on_fit_start(self, trainer: Trainer,
                     pl_module: LightningModule) -> None:
        optimizer = trainer.strategy._lightning_optimizers[0]._optimizer

        if len(trainer.optimizers) > 1:
            raise MisconfigurationException(
                "SparseML only supports training with one optimizer.")

        if self.steps_per_epoch is None:
            self.steps_per_epoch = trainer.estimated_stepping_batches

        optimizer = self.manager.modify(pl_module,
                                        optimizer,
                                        steps_per_epoch=self.steps_per_epoch,
                                        epoch=0)

        trainer.strategy._lightning_optimizers[0]._optimizer = optimizer

    def on_fit_end(self, trainer: Trainer, pl_module: LightningModule) -> None:
        self.manager.finalize(pl_module)

    @staticmethod
    # TODO: check for TrainingMode.EVAL
    def export_to_sparse_onnx(model: LightningModule,
                              output_dir: str,
                              sample_batch: Optional[torch.Tensor] = None,
                              name: str = "model.onnx",
                              opset: int = 14,
                              disable_bn_fusing: bool = True,
                              convert_qat: bool = True,
                              **export_kwargs: Any) -> None:
        """Exports the model to ONNX format."""
        exporter = ModuleExporter(model, output_dir=output_dir)
        sample_batch = sample_batch if sample_batch is not None else model.example_input_array  # type: ignore[assignment] # noqa: E501
        if sample_batch is None:
            raise MisconfigurationException(
                "To export the model, a sample batch must be passed via "
                "``SparseMLCallback.export_to_sparse_onnx(model, output_dir, sample_batch=sample_batch)`` "
                "or an ``example_input_array`` property within the LightningModule"
            )
        exporter.export_onnx(
            sample_batch=sample_batch,
            name=name,
            opset=opset,
            disable_bn_fusing=disable_bn_fusing,
            convert_qat=convert_qat,
            **export_kwargs,
        )
```

**Comment by bfineran** [comment]
Hi @clementpoiret does the export with the warning still produce a valid ONNX model? Could you also paste the warning if you have it?

**Comment by clementpoiret** [comment]
@bfineran it sounds like it is valid. Here is the code I use to save the model: 

```python
# Export to ONNX
clf.eval()
clf.training = False
sparseml.export_to_sparse_onnx(
    clf,
    output_dir="./sparseml_models/",
    name="sparse_model.onnx",
    sample_batch=torch.randn(1, 1, 28, 28),
    # opset_version=17,
    opset=14,
    disable_bn_fusing=False,
    convert_qat=True,
    input_names=["input"],
    output_names=["output"],
    dynamic_axes={
        "input": {
            0: "batch_size"
        },
        "output": {
            0: "batch_size"
        },
    },
)
```

And the warning:

```
/home/clementpoiret/micromamba/envs/torch211/lib/python3.10/site-packages/torch/onnx/utils.py:823: UserWarning: It is recommended that constant folding be turned off ('d
o_constant_folding=False') when exporting the model in training-amenable mode, i.e. with 'training=TrainingMode.TRAIN' or 'training=TrainingMode.PRESERVE' (when model is
 in training mode). Otherwise, some learnable model parameters may not translate correctly in the exported ONNX model because constant folding mutates model parameters. 
Please consider turning off constant folding or setting the training=TrainingMode.EVAL.
```

passing training=TrainingMode.EVAL has no effect as it seems overwritten later on.

**Comment by bfineran** [comment]
Hi @clementpoiret, yes it looks like it does get overwritten here - https://github.com/neuralmagic/sparseml/blob/239db8267a3e4df7fd074fb93d9e54ab99a96648/src/sparseml/pytorch/utils/exporter.py#L560
the reason why seems to be lost in the commit history, but we can dig a bit more. If you can make edits to your local install, you can try switching preserve to eval here. 
Additionally, tou can try running an eval and benchmark on your exported model to see if it meets your accuracy/performance needs in case the warning is not material.

**Comment by clementpoiret** [comment]
Thanks for your answer. Do you know the practical implications of saving a model in training mode? Will the onnx file be bigger or the inference slower?

**Comment by bfineran** [comment]
Not sure of any specific examples, but if the model behaves differently in training vs eval (batch norm updates, dropout, etc) these operations may be represented in the trace

**Comment by jeanniefinks** [comment]
Hi @clementpoiret 
As it's been some time without further discussion, I am going to go ahead and close this thread. However, feel free to re-open if there is further comment.
Thank you! 👋🏼 

Jeannie / Neural Magic
