### ISSUE TITLE
Pruning Implementation

### ISSUE THREAD

**Issue by March-08** [neuralmagic/sparseml#185]
Hi,

I was wondering, how did you implement the unstructured pruning method? 
Did you use a mask matrix to set the parameters to zero? And how did you prevent the update of those parameters set to zero?
And in general, how do you get speed from compression and evaluate on CPU as fast as on GPU? 
Thank you in advance!

**Comment by jeanniefinks** [comment]
Hi @March-08 We will be moving this post to our support forum and will respond there soon. Great questions!
- Jeannie, Neural Magic
