### ISSUE TITLE
Adding a `.pre-commit-config.yaml` file for maintaining consistent style and code quality.

### ISSUE THREAD

**Issue by Sai-Suraj-27** [neuralmagic/sparseml#1913]
**Is your feature request related to a problem? Please describe.**
Not, a problem but this can be a great enhancement to the codebase. 

**Describe the solution you'd like**
I'm thinking about adding a pre-commit configuration file (`.pre-commit-config.yaml `) to the codebase as it helps improve the code quality and maintain consistency within the project. It will allow all the developers/future contributors to maintain a consistent code style. Adding this will help us by running some automated checks before anyone tries to make a commit.
Many (Almost all) good Python based organizations/repos maintain a pre-commit configuration file for these benefits.

**Describe alternatives you've considered**

**Additional context**
I have a good experience in adding this file to large codebases (https://github.com/unifyai/ivy/pull/22220, https://github.com/unifyai/ivy/pull/22974, https://github.com/gprMax/gprMax/pull/354,  ) 
So, if you think it is useful let me know I will make a PR, Thank you.

**Comment by bfineran** [comment]
Hi @Sai-Suraj-27 take a look at our `Makefile` - we standardize to use `make style` for linting and then have on PR actions that run `make quality` to check.

We haven't actively looked at adding a pre commit config, but maybe `make style` could fit in

**Comment by jeanniefinks** [comment]
Hi @Sai-Suraj-27 
Happy New Year; let us know your thoughts on the last comment from @bfineran, thanks!

Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello @Sai-Suraj-27 
As it's been some time without a response, I am going to ahead and close this issue. If you want to continue the conversation, feel free to re-open thread.
Regards,
Jeannie / Neural Magic
