### ISSUE TITLE
Oriented Bounding Box support

### ISSUE THREAD

**Issue by Fritskee** [neuralmagic/sparseml#1960]
**Is your feature request related to a problem? Please describe.**
As of last week, ultralytics added support for yolo-v8 with oriented bounding boxes (obb). I was wondering whether this will also be supported by sparseML, such that we can create highly optimised/sparsified obb models? 

**Describe the solution you'd like**
Training and optimising (pruning + quantizing) a yolo model that can handle oriented bounding boxes

**Describe alternatives you've considered**
Currently I am using the yolo-v5 OBB repo (which is a fork from ultralytics) and I have my yolo-v8 obb model in training. However, these cannot be optimised to the extent that I want. Even after exporting to ONNX (which only supports half precision) or TensorRT (with int8) it's too large and slow. On the other hand, the neuralmagic models do fit all requirements I want to achieve.

**Comment by jeanniefinks** [comment]
Hi @Fritskee 
This is not on the Neural Magic Roadmap at the moment; however, if you are interested in making a contribution on the YOLO upstream or sparseml, it would certainly be looked at. I'll close this for now, but please re-open if you want to further the discussion. If something changes with our roadmap, we'll circle back.

Thank you!
Jeannie / Neural Magic
