### ISSUE TITLE
Checkpoint path for integrations/timm not parsed

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#197]
**Describe the bug**
Checkpoint path returned by `zoo_model.download_framework_files(extensions=[".pth"])` is of `List[str]` type.
https://github.com/neuralmagic/sparseml/blob/0c8b1d4533ab43159a1ac34c5b9c250027f6b2e7/integrations/timm/train.py#L392
`create_model(...)` from the `timm` repo expects a `str` type (only one path)
https://github.com/neuralmagic/sparseml/blob/0c8b1d4533ab43159a1ac34c5b9c250027f6b2e7/integrations/timm/train.py#L397

**Expected behavior**
To have: `args.initial_checkpoint = "model.pth"` instead of `args.initial_checkpoint = ["model.pth"]`.

**To Reproduce**
Exact steps to reproduce the behavior: use a local recipe and a SparseZoo checkpoint.
```shell
python integrations/timm/train.py \
  /PATH/TO/DATASET/imagenet/ \
  --sparseml-recipe /PATH/TO/RECIPE/recipe.yaml \
  --initial-checkpoint zoo:model/stub/path \
  --dataset imagenet \
  --batch-size 64 \
  --remode pixel --reprob 0.6 --smoothing 0.1 \
  --output models/optimized \
  --model resnet50 \
  --workers 8 \
```

**Errors**
`stat: path should be string, bytes, os.PathLike or integer, not list`

**Comment by markurtz** [comment]
Fixed with the PR that was merged in, not sure why this didn't close out once that went in.
