### ISSUE TITLE
Feature Request: Oriented Bounding Box Sparsification for YOLOv5/YOLOv8 on Custom Models/Datasets

### ISSUE THREAD

**Issue by salwaghanim** [neuralmagic/sparseml#2060]
**Description**:

I am writing to request support for oriented bounding box (OBB) sparsification within SparsML for custom models and datasets using YOLOv5 and YOLOv8. Currently, SparsML offers sparsification for axis-aligned bounding boxes, but for my use case, I require the ability to work with objects represented by OBBs.

**Benefits**:

1. Improved accuracy: OBBs can better represent objects with non-rectangular shapes, leading to more accurate localization and detection.
2. Wider applicability: This feature would expand SparsML's usability to various domains where OBBs are common, such as aerial imagery, traffic scene analysis, and autonomous driving.
3. Consistency with model architectures: Supporting OBBs aligns with the capabilities of popular YOLOv5 and YOLOv8 models, streamlining user workflows.

**Comment by jeanniefinks** [comment]
Hi @salwaghanim 
This is not on the Neural Magic Roadmap at the moment; however, if you are interested in making a contribution on the YOLO upstream or sparseml, it would be certainly looked at. I'll close this for now but please re-open if you want to further the discussion.
Jeannie / Neural Magic
