### ISSUE TITLE
yolov5 sparse fine tuning error

### ISSUE THREAD

**Issue by edelah** [neuralmagic/sparseml#2193]
**Describe the bug**
Taken from this tutorial [https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparse-transfer-learning.md#sparse-transfer-learning-yolov5s-onto-voc](url)

In a notebook in studiolab sagemaker, I run this code:

!sparseml.yolov5.train \
   --cfg yolov5n.yaml \
   --weights zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/pruned40_quant-none?recipe_type=transfer_learn \
   --recipe zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/pruned40_quant-none?recipe_type=transfer_learn \
   --data VOC.yaml \
   --patience 0 \
   --hyp hyps/hyp.finetune.yaml

and got the **error: 
"ValueError: Quantization can not be applied more than once. Loaded quantized model from checkpoint and detected quantization modifier in sparsification recipe. This is unsupported behavior. Ending run."**

Same problem with other pruned yolov5n model taken from the zoo.
Other examples in the page are working fine. 

**Expected behavior**
Training should run without errors. 
**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Ubuntu 20.04.3 LTS
2. Python version [e.g. 3.7]: 3.9.16
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: sparseml[yolov5]
4. ML framework version(s) [e.g. torch 1.7.1]: torch 2.1.2
5. Other relevant environment information [e.g. hardware, CUDA version]:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

**Comment by bfineran** [comment]
Hi @edelah try switching the -weights value to a non quantized value `zoo:yolov5-n-coco-pruned40`, you can keep the recipe the same and it should only apply the quantization once

**Comment by jeanniefinks** [comment]
Hi @edelah 
As some time has passed with no further updates, I am going to go ahead and close out this issue.
Please re-open if you want to continue the conversation.
Best, Jeannie / Neural Magic
