### ISSUE TITLE
'LeakyReLU' object has no attribute 'activation_post_process'

### ISSUE THREAD

**Issue by IdoZach** [neuralmagic/sparseml#266]
When trying to run a quantization recipe on a model with Leaky ReLUs, I get this error, raised by `return self.activation_post_process(output)`. 

Thanks.

**Comment by markurtz** [comment]
Hi @IdoZach do you have an example recipe and model/pipeline that we could take a look at to debug?

**Comment by jeanniefinks** [comment]
Hi @IdoZach, Circling back here to see if you're able to provide an example recipe and model/pipeline per Mark's last comment? Thank you!

**Comment by jeanniefinks** [comment]
Hello @IdoZach Looks like there is no further comments on this issue so we'll close this out for you. Definitely re-open it if you would like to engage.

Jeannie / Neural Magic
