### ISSUE TITLE
does sparseml support calculation of memory consumption per sample?

### ISSUE THREAD

**Issue by james20141606** [neuralmagic/sparseml#271]
Hi, I wonder if sparseml provides tools to calculate the memory consumption per sample? I mean the feature map size in every layer. For the standard feature map size calculation I know there are some tools. I don't know if sparseml has some unstructural pruning techniques which could enable less feature map memory consumption. If sparseml has such kind of pruning techniques I don't know some tools like [torchstat](https://github.com/Swall0w/torchstat) could still calculate the correct feature map memory.

**Comment by james20141606** [comment]
one more question about structural and unstructural pruning: after I run https://github.com/neuralmagic/sparseml/blob/fe5523fe7887a86a5909fd72a531f4577fab358a/notebooks/pytorch_classification.ipynb I found that the model becomes more sparse but it is not structural pruning? If we could not do structural pruning, could we still save memory (especially feature map memory)?

**Comment by james20141606** [comment]
Hi, after digging in to the codes and the paper more, I found that presumably sparseml is not designed to do structural pruning? I could find two types of structural pruning for filter and channel. But it seems they are not used in the recipes? (I also found there is a bug if use mask_type: filter then line 429 in https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/pytorch/optim/mask_creator_pruning.py will have an error, but it could be fixed easily. Another bug is if I choose mask_type: channel, it will report a bug since the last fully connected layer does have dimension >=3). I also wonder if these two types of structural pruning are just some standard ways, but not some innovative ways? It seems like having L_1 on filter or channel and do the pruning?

**Comment by markurtz** [comment]
Hi @james20141606, structured pruning is unfortunately not well supported currently. It is enabled to be able to introduce zeros along block dimensions such as channel and filter pruning, but it currently does not cut away those zeroed dimensions to save on memory. We have some work identified for the next few months to begin significantly upgrading our structured pruning techniques and I'll be sure to include and update here once that work begins and progresses.

Unstructured sparsity, unfortunately, is not supported for memory savings in any current training frameworks. We are actively working on support for this in the DeepSparse engine, however, for inference.

For torchstat, it is currently not well supported for sparse networks and unfortunately won't update information for zeroed parameters. We additionally have some work over the next month to upgrade our analysis pipelines which will be similar to what torchstat does. I'll update here once that lands as well.

We'll definitely look into the issue with channel pruning on fully connected layers and get that assigned for a fix, thank you for bringing that up!

Finally, magnitude pruning over longer time schedules generally beats out more of the innovative ways such as L1 or L0 regularization. There is some interesting research in this direction, though, and we're hoping to push out some more documentation and blog posts on this subject, so stay tuned for that!

**Comment by markurtz** [comment]
Hi @james20141606, with our recent 0.9 release we added further structured pruning support with a new modifier called StructuredPruningModifier for PyTorch. This should fix the issues you were seeing around the channel pruning support. Let us know if you have a chance to use it and happy to walk through some examples with it!

Thanks,
Mark
