### ISSUE TITLE
Do we currently support TensorFlow v2, and if not, are there any plans to support it?

### ISSUE THREAD

**Issue by zhaohb** [neuralmagic/sparseml#272]

**Comment by markurtz** [comment]
Hi @zhaohb, currently we do not have support for TF v2 outside of the Keras APIs. Do you have an example implementation we could look through for what it might take to support? The dynamic graph introduced in TF v2 makes it a bit harder for us to implement our general modifiers approach, but an example would help nail down the scope of what it would take.

 If what you're working with can go through the Keras APIs in TF v2, though, we'd recommend trying that route. Pruning is currently supported and quantization is on the near-term roadmap through those. Examples for pruning in Keras can be found [here](https://github.com/neuralmagic/sparseml/tree/main/integrations/keras).

**Comment by jeanniefinks** [comment]
Hi @zhaohb 
As there have been no further comments on this topic, we'll close this out. Feel free to re-open it if you have a follow-up. Thank you.

Regards, Jeannie / Neural Magic
