### ISSUE TITLE
Training yolo-v3 models sometimes results in checkpoints that cannot be loaded correctly

### ISSUE THREAD

**Issue by ohaijen** [neuralmagic/sparseml#316]
Hi SparseML team.

**Describe the bug**
When I train models, in some cases I cannot load them into the test.py tool. Specifically I get an error message at this line that tells me I cannot change requires_grad flag of non-leaf variables.

Interestingly, this seems to happen only when training on coco, but not voc or coco128.

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]:
2. Python version [e.g. 3.7]:
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]:
4. ML framework version(s) [e.g. torch 1.7.1]:
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:

I am using the sparseml/integrations/ultralytics-yolov3 sparseml integration as described in that readme. My HEADs are set to:
sparseml repo: 5713665bb69582f56c1ec7ac9a93a3dbd8578b42 (note: I don't use the pip version of sparse ml, I source the code in src/ directly)
yolov3 repo: e3bbbad5431f4a3c600547c79f968be540886310
 OS: Ubuntu 18
Torch:  1.7.1
Cuda 11.2

**To Reproduce**
Exact steps to reproduce the behavior:
Train model:
CUDA_VISIBLE_DEVICES=0,5,6,7 python -m torch.distributed.launch --master_port=654327 --nproc_per_node 4 train.py --workers 16 --batch 32 --img 512 --weights PRETRAINED_WEIGHTS --data data/coco128.yaml --hyp ../data/hyp.pruned.yaml --recipe ../recipes/short-yolov3-gmp.85.acdc.md --cfg models/yolov3-spp.yaml --disable-ema

(note that the exact recipe doesn't seem to matter, I just made a really short one)

Test model:
CUDA_VISIBLE_DEVICES=1 python test.py --weights runs/train/exp81/weights/last.pt

train.py and test.py are located in sparseml/integrations/ultralytics-yolov3/yolov3

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

Namespace(augment=False, batch_size=32, conf_thres=0.001, data='data/coco128.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights=['runs/train/exp81/weights/last.pt'])
YOLOv3 🚀 v9.5.0-33-g62c06bb torch 1.7.1 CUDA:0 (GeForce RTX 2080 Ti, 11019.4375MB)

Fusing layers...
Model Summary: 269 layers, 62971933 parameters, 62971933 gradients, 157.1 GFLOPS
Traceback (most recent call last):
  File "test.py", line 328, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 59, in test
    model, extras = load_checkpoint('ensemble', weights, device)  # load FP32 model
  File "/nfs/scistore14/alistgrp/eiofinov/sparseml/integrations/ultralytics-yolov3/yolov3/models/export.py", line 70, in load_checkpoint
    p.requires_grad = True
RuntimeError: you can only change requires_grad flags of leaf variables.

NOTE: wrapping the offending line in a try statement or just saying if p.is_leaf fixes the problem and leads to test output. But this is probably not ideal :)

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by markurtz** [comment]
Thanks for bringing this to our attention @ohaijen, we'll dive into this more this week to see about a resolution.

**Comment by jeanniefinks** [comment]
Hi @ohaijen 
We could not reproduce this error; in October, we will be having a software release. We will circle back and see if you're still having this issue. Thank you for your patience.

**Comment by jeanniefinks** [comment]
Hello @ohaijen 
With our last release deployed at the end of October, we wanted to check in and see if you were still experiencing this issue? Let us know your experience! We're happy to assist. 
Best, Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello @ohaijen 
As there have been no further comments on this, we will close out this issue. Feel free to re-open it however if you would like to continue the conversation. 
Thank you! Jeannie / Neural Magic
