### ISSUE TITLE
Baseline Dense FP32 Performance

### ISSUE THREAD

**Issue by OrkhanHI** [neuralmagic/sparseml#340]
Hi,

I would like to know whether you applied any Neural Magic technique to get the baseline Dense FP32 model performance?

Thanks.

**Comment by mgoin** [comment]
Hi there,

The DeepSparse Engine uses the best execution algorithms for the given model and given hardware. For baseline Dense FP32 models we can choose to use spatially sparse algorithms like winograd or activation sparsity if the model allows for it, alongside our depthwise execution model.

From the SparseML side we don't apply any optimizations to the baseline Dense FP32 models we benchmark. Hope that clears it up.

- Michael

**Comment by jeanniefinks** [comment]
Hello @OrkhanHI 
It appears you are all set and do not need further assistance. If you have additional questions about Michael's response, please reopen this issue. 

Be sure to check out our posts at [https://neuralmagic.com/blog/](https://neuralmagic.com/blog/) for the latest developments. We've also released an alpha website for SparseZoo, our model repository, at [https://sparsezoo.neuralmagic.com](https://sparsezoo.neuralmagic.com) - check it out!

Regards and thank you, Jeannie // Neural Magic
