### ISSUE TITLE
what is recipe?

### ISSUE THREAD

**Issue by jeannotes** [neuralmagic/sparseml#350]
thanks for the great work, but I was wondering that what is the recipe that is one of the arguments?
how to write recipe according to different tasks, such as:detection, segmentation,
there are recipes in your examples, which is hard for understanding, could you give tutorials ?
thanks

**Comment by bfineran** [comment]
Hi @jeannotes thank you for the feedback!  A recipe is a YAML file that defines a series of objects for modifying the training process for sparsification.  An intro to them can be found here: https://docs.neuralmagic.com/sparseml/source/recipes.html.

To perform sparsification such as pruning and quantization, the modifiers will be the same across models/tasks - the main thing that may change between them is if any specific model parameters are named, then they should be updated for the model the recipe is applied to.

Let me know if this response and doc help as well as any other specific processes that you think a tutorial would be helpful for.

**Comment by jeanniefinks** [comment]
Hello @jeannotes It looks like you have no further comments so we'll close this issue out. If you have further comments related to this topic, please re-open the issue. We'd love to hear what you think!

Jeannie / Neural Magic
