### ISSUE TITLE
Update model weights in tutorial docs.

### ISSUE THREAD

**Issue by mihir135** [neuralmagic/sparseml#392]
**What is the URL, file, or UI containing proposed doc change**
https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md

**Where does one find the original content or where would this change go?**
https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md#applying-a-recipe

**What is the current content or situation in question**
The current doc contains incorrect weights sizes.

**What is the proposed change**
Updated the weights, PR - https://github.com/neuralmagic/sparseml/pull/391/commits/2454c0b97010e872846727036eddb7c60b0ebf7a

**Additional context**
Old  - 
![old_ref](https://user-images.githubusercontent.com/40884708/133975173-4e6a76a9-9e45-4c88-ab4d-b83640a65c06.png)
New-
![new_refs](https://user-images.githubusercontent.com/40884708/133975185-611b72e1-7005-43ca-9cf5-654812526ff6.png)

**Comment by mgoin** [comment]
@mihir135 thank you for finding, thoroughly documenting this issue, and putting up a fix! gave you a review, very much appreciated

**Comment by mgoin** [comment]
landed #391
