### ISSUE TITLE
YOLOv3-tiny Pruning Recipe

### ISSUE THREAD

**Issue by anujdutt9** [neuralmagic/sparseml#396]
Hi, is there any recipe provided for pruning the YOLOv3-tiny model ? I could see the recipe for YOLOv3-SPP model but couldn't fine one for the tiny model.
Can you please share a recipe for that or provide a guide for making one for the tiny model?

Thanks.

**Comment by markurtz** [comment]
Hi @anujdutt9, we've recently added an API to enable a simpler flow for creating recipes in our 0.9 SparseML release. This should address your needs and give you a great starting point for a recipe. To run it first export the YOLOv3-tiny model to ONNX and then use the following SparseML code to create the recipe:

`
from sparseml.sparsification import create_pruning_recipe

ONNX_FILE_PATH = "/PATH/TO/MODEL.onnx"
create_pruning_recipe(ONNX_FILE_PATH)
`
