### ISSUE TITLE
pruned yolov5 unchanged parameter count

### ISSUE THREAD

**Issue by MrOCW** [neuralmagic/sparseml#408]
Hi, I tried the yolov5 tutorials with --recipe = yolov5s.pruned_quantized.md
The QAT works as I can see fake quantized modules in netron but the number of parameters remain unchanged. 
Are there any additional steps to take to remove the pruned parameters?
Thanks!

**Comment by markurtz** [comment]
Hi @MrOCW, the type of pruning we are doing for the YOLOv5 models is unstructured. These parameters are removed by setting the value to 0. You should see during training in the PyTorch weights the 0's slowly introduced into the models with the recipes. On export to ONNX, you should additionally see the 0's in the weight matrices. If the model is quantized, the zeros will be set to the zero point -- 127 for example for some flows.

**Comment by rahul-tuli** [comment]
Hi @MrOCW, elaborating on @markurtz's explanation, for unstructured sparsity the number of parameters remains same only some percentage of them are made 0, to observe the advantage/speed-up from the 0's introduced you would need a runtime engine that can leverage sparsity in the weight matrices such as Neural Magic's [DeepSparse](https://github.com/neuralmagic/deepsparse) engine. To answer your question, the zeros introduced are the "removed/pruned" parameters

**Comment by jeanniefinks** [comment]
Hi @MrOCW 
It looks like there are no further questions on this topic so we'll close out this thread. Feel free to re-open if you do! 
Best, Jeannie / Neural Magic
