### ISSUE TITLE
Unified naming convention

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#426]
**Is your feature request related to a problem? Please describe.**
It might be worth considering a unified naming convention for these attributes:
```python
        # initialize masks to all ones
        self._param_masks = [torch.ones(param.shape) for param in self._params]
        self._params_init = [None] * len(self._layers)  # type: List[Tensor]
        self._params_unmasked = [None] * len(self._layers)  # type: List[Tensor]
        self._params_grad = [None] * len(self._layers)  # type: List[Tensor]
        self._params_movement = [None] * len(self._layers)  # type: List[Tensor]
````
**Describe the solution you'd like**
Either all with `self._param_*` or all with `self._params_*`. Then we wouldn't need to check `__init__` to see if an attribute starts with `param` or `params`. This would probably make these things easier to identify: https://github.com/neuralmagic/sparseml/pull/424

**Comment by markurtz** [comment]
Hey @eldarkurtic, this is a great point that we should get updated. We'll create an internal ticket to address. If you'd like to push up a change as well feel free and we'll get it reviewed and landed.

**Comment by markurtz** [comment]
Hey @eldarkurtic, we've gone through a refactor of the pruning modifiers with the 0.11 release and with that the code has changed to be more standardized. I'm going to close this out for now and feel free to reopen or open up a new one with any other suggestions!
