### ISSUE TITLE
"Error(s) in loading state_dict for Model:" when I try to export a model edited with a recipe

### ISSUE THREAD

**Issue by antimo22** [neuralmagic/sparseml#437]
Hi, I have trained a yolov5s model for several epochs, and I followed the tutorial to apply a recipe to it. At the export step, I have this error:

RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "model.0.conv.conv.quant.activation_post_process.scale", "model.0.conv.conv.quant.activation_post_process.zero_point", ...

	Unexpected key(s) in state_dict: "model.0.conv.conv.weight", "model.0.conv.conv.bias", "model.1.conv.weight", "model.1.conv.bias", ...

Someone can help me?

**Comment by bfineran** [comment]
Hi @antimo22 it looks like you are trying to export a model with a quantization recipe with non quantized weights (ie weights obtained from epoch 1). This will cause issues because the export script will expect the checkpoint to have quantized weights.

When you notice the weight file size increase, this is likely when quantization begins as extra parameters are injected to track the quantization (such as  `"model.0.conv.conv.quant.activation_post_process.scale"`). Have you tried exporting from one of these checkpoints?

**Comment by antimo22** [comment]
Yes, I tried to export the model from the epoch 6, that is around 114 MB. Should I have to continue the training for more epochs?

**Comment by bfineran** [comment]
stopping early depends on the amount of recovery you are looking to get. Additionally, to get a quantized checkpoint, you must stop after quantization has been applied in the recipe. Could you point me to the exact recipe you are using? If quantization is applied before epoch 6, then you should be fine to export, recovery aside.

**Comment by antimo22** [comment]
This is the recipe I've applied: https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/recipes/yolov5s.pruned_quantized.md

I see something like pruning_end_epoch 100, so I have to train for 100 epochs to end the pruning process?
BTW, I used also the epoch 10 with weights around 140MB, still the same error.

**Comment by markurtz** [comment]
Hi @antimo22, this recipe was created originally for the COCO dataset. Other datasets can require more or fewer epochs and this is a hyperparameter that you should feel free to edit. We're also going to be updating some new flows to make the editing of these hyperparams in recipes easier. 

If you have a chance, could you try and run one of the transfer recipes such as this one: https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/recipes/yolov5.transfer_learn_pruned_quantized.md This will run in a shorter amount of time. If you'd like to run for fewer epochs then we'd recommend editing the recipe and changing the num_epochs and the quantization_start_epoch to smaller values that meet your requirements.

**Comment by jeanniefinks** [comment]
Hi @antimo22 
Checking in here to see if you were able to try out one of our recommended recipes? We're happy to help.
Thanks!
Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello @antimo22 
As there have been no further comments on this, we will close out this issue. Feel free to re-open it however if you would like to continue the conversation. Thank you!
Jeannie / Neural Magic

**Comment by dnth** [comment]
To anyone facing the same issue - I had the same problem as @antimo22 and confirm that the solution by @markurtz works!
