### ISSUE TITLE
Can't get attribute 'SPPF'

### ISSUE THREAD

**Issue by yDing121** [neuralmagic/sparseml#492]
**Describe the bug**
I get  `Can't get attribute 'SPPF' on <module 'models.common' from 'PATH_TO_DIR/sparseml/integrations/ultralytics-yolov5/yolov5/models/common.py'>` when I try to train using train.py from the yolov5 within sparseml

**Expected behavior**
train.py should train my model

**Environment**
1. OS [e.g. Ubuntu 18.04]: Windows 10
2. Python version [e.g. 3.7]: 3.7 (Conda)
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.9.0
4. ML framework version(s) [e.g. torch 1.7.1]: torch 1.7.0
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:
IDE: PyCharm 2021.3
GPU: NVIDIA GeForce RTX 2080 Founders Edition
CPU: AMD Ryzen 5 3600
CUDA:
![image](https://user-images.githubusercontent.com/87789514/147138462-991e7e69-67c7-4030-a180-33a4cb1e648c.png)

**To Reproduce**
(anaconda prompt)
Clone sparseml repository
cd to integrations/ultralytics-yolov5
run setup_integration.sh
cd to yolov5
python train.py --cfg ../models/yolov5s.yaml --weights yolov5s.pt --data D:/Projects/Python/ML/Aimbot/yolov5/data/12-22_V1.yaml --hyp data/hyp.scratch.yaml

**Errors**
![image](https://user-images.githubusercontent.com/87789514/147139547-514a484a-1776-4f8c-9188-e1a718f39db5.png)
![image](https://user-images.githubusercontent.com/87789514/147139583-cd41c0c7-baf0-4cc1-b7b2-551ecd442d50.png)
![image](https://user-images.githubusercontent.com/87789514/147138726-023a5e4b-cc18-4023-ada5-5a7dd0fb46bf.png)

**Additional context**
I was able to train the model with the exact same command (file paths adjusted accordingly) with standalone yolov5 on a standalone local directory, however this issue only arises when I try to train using the yolov5 within sparseml/integrations/ultralytics-yolov5.

**Comment by markurtz** [comment]
Hi @yDing121, we believe the issue happening here is the default weights loading from Ultralytics are improperly serialized and conflicting with the local Windows environment. Could you try and replace `--weights yolov5s.pt` with `--weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none`?

One note I want to call out, though, is that we currently have limited support for Windows platforms and is not part of our current pathways for testing. If you have access to a Linux server or VM this also may remedy the issue.

Thanks,
Mark

**Comment by markurtz** [comment]
Hi @yDing121, the fix for this is up on our nightly now (pip install sparsify-nightly). Can you try it out and let us know if you have any issues? Will follow up once this is live on our main release pathway as well.

**Comment by yDing121** [comment]
Hey Mark,

I will be testing this shortly.

**Comment by kuonumber** [comment]
@yDing121 I followed your guide to install sparsify-nightly but got the same Can't get attribute 'SPPF' error.
Then I found similar issue from yolov5 official github. [AttributeError: Can't get attribute 'SPPF' #5175](https://github.com/ultralytics/yolov5/issues/5175). The post suggested that we can downgrade our yolov5.pt to tag v5.0.
It works for me.

**Comment by jeanniefinks** [comment]
Thank you @kuonumber for your update! Glad to hear it worked! 
@yDing121 Let us know if you found similar success. 

Best, Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
With no further comments on this thread, I am going to go ahead and close this issue. Please feel free to re-open if you want to continue the conversation. If you feel inclined, please ⭐ our repo if not already; we appreciate the community support! [https://github.com/neuralmagic/sparseml/stargazers](https://github.com/neuralmagic/sparseml/stargazers)
Thank you! 
Jeannie / Neural Magic
