### ISSUE TITLE
Error: No module named 'sparseml'

### ISSUE THREAD

**Issue by RasoulZamani** [neuralmagic/sparseml#610]
Hi, im using sparseml yolov5 integration. as you said in totorial for transfer learning I run this code:

python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned_quantized.md

(I run this bash script in train.py folder i.e: sparseml/integrations/ultralytics-yolov5/yolov5)

but I get this error:
.../models/export.py", line 20, in <module>
    from sparseml.pytorch.utils import ModuleExporter
ModuleNotFoundError: No module named 'sparseml'

it seems that it cant impoort from sparseml module
is it a bug? or I am doing sth wrong?
thanks!

**Comment by RasoulZamani** [comment]
one day pass ...
 is there any one to comment my issue? 
:)

**Comment by rahul-tuli** [comment]
Hi @RasoulZamani, it seems you don't have `sparseml` installed, could you attach the output from `pip show sparseml`

**Comment by RasoulZamani** [comment]
thanks @rahul-tuli , 
 yes ,I've installed spaeseml first, for beeing sure, the output of pip show as you want is: 

(RZ_quant) fteam@fteam:~/Desktop/naser/R.Zamani/Quantization/sparseml/integrations/ultralytics-yolov5/yolov5$ pip show sparseml
Name: sparseml
Version: 0.11.0
Summary: Libraries for applying sparsification recipes to neural networks with a few lines of code, enabling faster and smaller models
Home-page: https://github.com/neuralmagic/sparseml
Author: Neuralmagic, Inc.
Author-email: support@neuralmagic.com
License: Apache
Location: /home/fteam/python-environments/RZ_quant/lib/python3.6/site-packages
Requires: pyyaml, onnx, tqdm, packaging, scikit-image, scipy, progressbar2, numpy, onnxruntime, psutil, jupyter, requests, toposort, GPUtil, merge-args, ipywidgets, pandas, matplotlib, sparsezoo, pydantic

**Comment by RasoulZamani** [comment]
is there any other idea ?

**Comment by markurtz** [comment]
Hi @RasoulZamani, we're looking into this now to see if we can replicate it. Will have a response by the end of the day.

Thanks,
Mark

**Comment by RasoulZamani** [comment]
Thanks dear @markurtz
 as I said in issue #611 , I manually copy sparse module to yolo root. but then another exception raised: 
ModuleNotFoundError: No module named 'sparseml.pytorch.utils.quantization
consider this too
thanks!

**Comment by bfineran** [comment]
Hi @RasoulZamani I left a comment about the issue in #611.

For this particular issue, could you describe the exact steps that led to produce it? Curious that pip shows that sparseml is installed but it is was not importable.

**Comment by RasoulZamani** [comment]
I saw you comment in #611, thanks very much, this error solved by your guidance in #611,  although another error raise! 
I close this issue to continue in #611.
