### ISSUE TITLE
ModuleNotFoundError: No module named 'sparseml.pytorch.utils.quantization'

### ISSUE THREAD

**Issue by RasoulZamani** [neuralmagic/sparseml#611]
**Describe the bug**
in running train.py for yolov5 integration in sparseml, I get error that no module sparseml , (i report it in another issue but no answer i have seen yet) so I manualyy copy sparseml from src to yolo module, but now it get another error that:

sparseml/integrations/ultralytics-yolov5/yolov5/models/export.py", line 21,

 from sparseml.pytorch.utils.quantization import skip_onnx_input_quantize
ModuleNotFoundError: No module named 'sparseml.pytorch.utils.quantization'

**Expected behavior**
I Expect importing properly! but when I check adress that export.py try to import, I find out that he/she is wright! there is no quantization module in sparseml.pytorch.utils. 

**Environment**
Include all relevant environment information:
1. OS : Ubuntu 18.04
2. Python version :3.7

**To Reproduce**
Exact steps to reproduce the behavior:
git clone sparseml, pip install sparseml, 
go to integration of yolov5 and bash setup
copy sparseml from src to yolo root (you didn't say that but if we don't copy, it cant recognize sparse module -I report this issue too but no answer received-)
go to yolo root
then run :

python3.7 train.py --data voc.yaml --cfg ../models/yolov5l.yaml --weights zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned_quant-aggressive_95?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned_quantized.md

**Errors**
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    import test  # import test.py to get mAP after each epoch
  File "/home/fteam/Desktop/naser/R.Zamani/sparseml/integratio   ns/ultralytics-yolov5/yolov5/test.py", line 12, in <module>
    from models.export import load_checkpoint
  File "/home/fteam/Desktop/naser/R.Zamani/sparseml/integratio   ns/ultralytics-yolov5/yolov5/models/export.py", line 21, in <m   odule>
    from sparseml.pytorch.utils.quantization import skip_onnx_   input_quantize
ModuleNotFoundError: No module named 'sparseml.pytorch.utils.q   uantization'

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by markurtz** [comment]
Hi @RasoulZamani, we're looking into this now to see if we can replicate it. Will have a response by the end of the day.

Thanks,
Mark

**Comment by RasoulZamani** [comment]
Hi dear @bfineran 
thanks for your guidance. I do what you said and error disappear  *-* ! , but another error arise :(  :

 CUDA error: no kernel image is available for execution on the device

when I google this new error , pople sugest me : 
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U
but when I run this, another error arise:
ImportError: required max torch version 1.9.100, found 1.11.0

so now what can I do?

**Comment by RasoulZamani** [comment]
I'm still waiting for help! pls don't forget me :)

**Comment by RasoulZamani** [comment]
Hi @bfineran 
after running your suggested command, error not arise again, but during processing, its show this massage:
 torch~=1.7.0 not found and is required by YOLOv5, attempting auto-update...
and then back to torch 1.7 again!(download  and install it) and if I run my command again, previous error come back!! :(
can you solve this inconsistency?

**Comment by markurtz** [comment]
Hi @RasoulZamani, unfortunately, we are currently hard coding the torch version to 1.7 in the yolov5 integration since that is the last official one that has been tested with that flow. Additionally, PyTorch has not compiled a cuda 11 compatible build for version 1.7. Until we're able to upgrade the flows and test (in process right now and we hope to have it completed in the next two weeks), the safest option is downgrading the cuda version to 10 to enable PyTorch 1.7.

An alternative, experimental pathway, for now, would be to edit the [requirements.txt file](https://github.com/neuralmagic/yolov5/blob/master/requirements.txt#L10) on your local setup to checkout torch 1.9 instead of 1.7. The risk here is whether or not the quantization flows will continue to work correctly. If you run into any issues with this please let us know and we'll be happy to jump on and support.

Thanks,
Mark

**Comment by RasoulZamani** [comment]
thanks @markurtz  and @bfineran for your answers.

**Comment by jeanniefinks** [comment]
Hi @RasoulZamani 

As it has been a few weeks with no further conversation, I am going to go ahead and close this comment. Please re-open if you have a follow-up. Also, I invite you to "star" our SparseML repo if you like and have not already! We always like seeing community support!
https://github.com/neuralmagic/sparseml/

Thank you!
Jeannie / Neural Magic

**Comment by dshirron2** [comment]
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
