### ISSUE TITLE
Save model function doesn't save the manager_state_dict from wrapped optimiser. 

### ISSUE THREAD

**Issue by Godofnothing** [neuralmagic/sparseml#616]
There is a utility function in the` pytorch.utils`:
https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/pytorch/utils/model.py
And there is a line that is expected to save manager, if the optimizer is wrapped by `ScheduledModifierManager`:
```
    if include_modifiers and optimizer and hasattr(optimizer, "manager_state_dict"):
        save_dict["manager"] = optimizer.manager_state_dict()
```
However `RecipeManagerStepWrapper` doesn't have this property. 
I think what was expected is something like this:
```
    if include_modifiers and optimizer and hasattr(optimizer, "wrapped_manager"):
        save_dict["manager"] = optimizer.manager.state_dict()
```
And then one can add `load_manager` in addition to the existing `load_model, load_optimizer`, `load_epoch`. 

Version
---
I am using the latest nightly release '0.12.0.20220316'

**Comment by bfineran** [comment]
thanks for the catch @Godofnothing. The current line in place saves the manager state for the predecessor to `RecipeManagerStepWrapper`, `ScheduledOptimizer`. #618 adds the support you suggested.

Just curious - what led you to discover this bug?

**Comment by bfineran** [comment]
thanks for sharing @Godofnothing! Feel free to check out our existing timm integration if you're interested (we've focused mostly on resnet50 and ViT there): 

https://github.com/neuralmagic/sparseml/tree/main/integrations/rwightman-timm
https://github.com/neuralmagic/pytorch-image-models
