### ISSUE TITLE
Recipe failure from Sparsify in SparseML

### ISSUE THREAD

**Issue by markurtz** [neuralmagic/sparseml#670]
Hi @tlrmchlsmth ,
Thanks for the fix. After install new verion:
```
deepsparse           0.11.2
sparseml             0.11.1
sparsezoo            0.11.0
sparsify             0.11.0
```
It seems that the old err is solved, but I got another err, please the the attached image.
![Screen Shot 2022-03-31 at 11 11 31](https://user-images.githubusercontent.com/7928673/160975266-8f11e808-b279-4339-ab7f-01524dc90244.png)
r

_Originally posted by @edwardnguyen1705 in https://github.com/neuralmagic/deepsparse/issues/279#issuecomment-1084055401_

**Comment by markurtz** [comment]
Hi @edwardnguyen1705 we're actively looking into this. In the interim, are there further details you could provide about the model and training pipeline you're using so we can get you a working recipe?

Thanks,
Mark

**Comment by jeanniefinks** [comment]
Hi @edwardnguyen1705 
Just checking in to see if you are able to provide more details about your model and training pipeline? 
Thank you! 
Jeannie / Neural Magic

**Comment by edwardnguyen1705** [comment]
> 

Thanks for asking,
I just tried a pre-trained public model: [`NanoDet-Plus-m-320`](https://github.com/RangiLyu/nanodet#model-zoo)

**Comment by markurtz** [comment]
Hi @edwardnguyen1705, we've landed this diff now on main and will be cutting out a hotfix release by early next week, will update here once that is available: https://github.com/neuralmagic/sparsify/pull/110

**Comment by dbogunowicz** [comment]
The hotfix is now in place. I am fairly confident we can close this for now.
