### ISSUE TITLE
How to properly load manager state dict with modifiers?

### ISSUE THREAD

**Issue by Godofnothing** [neuralmagic/sparseml#692]
I am running a training of a model with a custom recipe involving several learning_rate modifiers and `MFACPruningModifier`.
I checkpoint the model using the `save_model` function `from sparseml.pytorch.utils`:

        save_model(
           path=#path-to-save,
           model=model, 
           optimizer=optimizer, 
           epoch=epoch,
           use_zipfile_serialization_if_available=True,
           include_modifiers=True
        )

But when attempting to restart from that checkpoint, having previously defined manager and modified it in the training script:

    manager = ScheduledModifierManager.from_yaml(args.sparseml_recipe)
    # wrap optimizer    
    optimizer = manager.modify(model, optimizer, steps_per_epoch=len(loader_train), epoch=start_epoch)
    # load state
    manager.load_state_dict(state_dict['manager'])

I encounter the following error due to incompatibility of keys:

`IndexError: Found extra keys: {'MFACPruningModifier-bc0da17c953429b213f11f560b1f58e9'} and missing keys: {'MFACPruningModifier-0eeb649660da3fc081520285feb4aa0b'}`

There is a suffix - some hash generated in some way. What should I do to make the hashes in the created manager and checkpoint equal? 

**Version**
`sparseml-nightly              0.12.0.20220405`

**Comment by markurtz** [comment]
Thanks for confirming all of that @Godofnothing. Additionally, can you confirm that nothing is changing with the MFAC modifier at all between the initial training run and the loading of the checkpoints (no changing of params or the general recipe)? If you have some reproducible code, that would help as well. We have active tests around the checkpoint loading, so trying to narrow down the conditions to replicate the issue.

**Comment by KSGulin** [comment]
@Godofnothing M-FAC it sounds like you're using gradient accumulation, which requires some warmup time to collect enough gradients for the M-FAC calculations. You can also provide a gradient sampler to the modifier, which samples enough gradients at a single fixed step in the training process. 

The tutorial [here](https://github.com/neuralmagic/sparseml/blob/main/research/mfac/tutorials/one_shot_pruning_with_mfac.md) outlines how to create a GradSampler. You can also see a sample implementation [here](https://github.com/neuralmagic/sparseml/blob/532461065182565e3e2ceb5d13921afdebbf8b6e/src/sparseml/transformers/sparsification/trainer.py#L148) and the definition for the GradSampler class [here](https://github.com/neuralmagic/sparseml/blob/532461065182565e3e2ceb5d13921afdebbf8b6e/src/sparseml/pytorch/utils/sparsification.py#L175).

Just to confirm, is this the error you're running into with M-FAC:
```
"MFAC pruning step called, but only {grads_collected} were collected from the expected {num_grads}."
```

**Comment by Godofnothing** [comment]
@KSGulin  many thanks for pointing out!

**Comment by Godofnothing** [comment]
@markurtz parameters of modifier are kept fixed - the `sparsities`, `weights`, e.t.c `yaml` recipe is kept unchanged. Yeah, I'll try to provide the precise context of the issue.

**Comment by Godofnothing** [comment]
@KSGulin  I would like to ask one more question. If am running gradual pruning with frequency of updates, say, one update per 10 epochs, do I understand correctly, that setting up like this at the start of training will do the job, or the instruction [here](https://github.com/neuralmagic/sparseml/blob/main/research/mfac/tutorials/one_shot_pruning_with_mfac.md) applies only for single-shot pruning?

```
manager = ScheduledModifierManager.from_yaml(args.sparseml_recipe)
# wrap optimizer    
optimizer = manager.modify(model, optimizer, steps_per_epoch=len(loader_train), epoch=start_epoch, grad_sampler=grad_sampler)
```

**Comment by KSGulin** [comment]
@Godofnothing exactly, the grad sampler can be used with gradual pruning just as you have it there. Let me know if any other M-FAC questions come up :-)
