### ISSUE TITLE
Runtime Error, no match for existing parameter

### ISSUE THREAD

**Issue by MaxFeli** [neuralmagic/sparseml#699]
While trying to train using pruning and quantization recipe on my yolov5s model, the error raised is the following:

in validate_all_params_found
    name_or_regex, found_param_names, name_or_regex_patterns
RuntimeError: All supplied parameter names or regex patterns not found. No match for **model.9.m.0.cv2.conv.weight** in found parameters ['model.7.conv.weight', 'model.8.cv2.conv.weight', 'model.13.m.0.cv2.conv.weight', 'model.17.cv2.conv.weight', 'model.18.conv.weight', 'model.20.cv2.conv.weight', 'model.20.cv3.conv.weight', 'model.20.m.0.cv2.conv.weight', 'model.21.conv.weight', 'model.23.cv2.conv.weight', 'model.23.cv3.conv.weight', 'model.23.m.0.cv2.conv.weight'].  Supplied ['model.23.m.0.cv2.conv.weight', 'model.21.conv.weight', 'model.23.cv3.conv.weight', 'model.23.cv2.conv.weight', 'model.20.m.0.cv2.conv.weight', 'model.18.conv.weight', **'model.9.m.0.cv2.conv.weight'**, 'model.7.conv.weight', 'model.20.cv3.conv.weight', 'model.20.cv2.conv.weight', 'model.8.cv2.conv.weight', 'model.13.m.0.cv2.conv.weight', 'model.17.cv2.conv.weight']

I've highlighted the strange fact: the parameter the function could not find belongs to the list of the available one.
Problem both with cpu or gpu.

Command sent:
python3 train.py --device cpu  --img 640 --batch 16 --epochs 1 --data '../data.yaml' --cfg ./models/yolov5${VERSION}.yaml --weights $PROJECT/yolov5${VERSION}_${MONTH}_${DAY}/weights/best.pt --project $PROJECT --name yolov5${VERSION}_${MONTH}_${DAY}_pruned_quantized --hyp data/hyps/hyp.scratch-med.yaml --recipe ../sparseml/integrations/ultralytics-yolov5/recipes/yolov5${VERSION}.pruned_quantized.md --cache

The work is running on a cluster provided by university, which is a linux-based modular environment. To make YOLO work, we loaded gcc/9.3 compiler and python/3.7.10, cuda toolkit 11.3. Sparseml version is 0.11.1, all necessary requirements are installed.

**Comment by markurtz** [comment]
Thanks for providing all this information @MaxFeli, we're looking into this now.

**Comment by KSGulin** [comment]
@MaxFeli the short answer is that you'll want to change the cfg command to look in **models_v5.0**. i.e.
`--cfg ./models_v5.0/yolov5${VERSION}.yaml`

The longer answer is that we recently updated our Yolov5 branch to catch up to the Yolov5 upstream and in between our updates, Ultralytics has updated the default Yolov5 architecture (to Yolov5{n/s/l/m/x}6). Our research team is working on creating recipes for optimal compression on the new architecture which we are planning to release shortly. 
In the meanwhile only the previous architecture (housed in `models_v5.0` is supported with off the shelf recipes, but you're still able to create your own recipes to work with the updated models (housed in `models/`). 

Thanks for reporting this. We'll update the documentation to make this distinction more clear, until the new recipes are released.

**Comment by MaxFeli** [comment]
Another big issue popped up. So I followed your advice and used, both in training and prunization, the command `--cfg ./models_v5.0/yolov5${VERSION}.yaml`. At first, actually, I used model from `models/` folder for training and from `models_v5.0/` for the prunization function, but error was exactly the same. I tried it either with Colab or with our custom environment described before, but it didn't work.

Error is "positional argument required missing", but I couldn't find how or where to fix it.
First command is `python3 train.py --device 0  --img 640 --batch 16 --epochs 300 --data ../data.yaml --cfg "./models_v5.0/yolov5${VERSION}.yaml" --weights '' --project $PROJECT --name yolov5${VERSION}_${MONTH}_${DAY} --hyp data/hyps/hyp.scratch-med.yaml --cache`
Second is `python3 train.py --device 0  --img 640 --batch 16 --epochs 300 --data ../data.yaml --cfg "./models_v5.0/yolov5${VERSION}.yaml" --weights $PROJECT/yolov5${VERSION}_${MONTH}_${DAY}/weights/best.pt --project $PROJECT --name yolov5${VERSION}_${MONTH}_${DAY}_pruned_quantized --hyp data/hyps/hyp.scratch-med.yaml --recipe ../sparseml/integrations/ultralytics-yolov5/recipes/yolov5${VERSION}.pruned_quantized.md --cache`

![Screenshot (90)](https://user-images.githubusercontent.com/80213715/164164650-be62a7a1-4054-4ebf-b4cd-48766c2d44de.png)
![Screenshot (91)](https://user-images.githubusercontent.com/80213715/164164663-2864ee42-6e95-4df8-9a49-4ba319810df5.png)

**Comment by KSGulin** [comment]
@MaxFeli this looks like an issue with an out of date sparseml version. Can you confirm your sparseml version is `>= 0.12`?

**Comment by MaxFeli** [comment]
Ok, that should be the problem! I'll check tomorrow and close the issue! Thanks

**Comment by jeanniefinks** [comment]
Greetings @MaxFeli 
A quick note that .12 has been cut this morning and hopefully should nip that issue you had.
Have a nice weekend! 🍺 
Jeannie / Neural Magic
