### ISSUE TITLE
Update README for one-shot runs with pruners that require gradients

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#761]
**Is your feature request related to a problem? Please describe.**
It would be a good idea to mention here https://github.com/neuralmagic/sparseml/blob/main/README.md#:~:text=Instead%20of%20training,manager.apply(model)
that one-shot pruning runs with pruners that use gradients require passing additional argument (`grad_sampler`) when calling into `manager.apply(model)`. If `grad_sampler` not provided, gradients won't be collected and the run will crash.

**Comment by jeanniefinks** [comment]
Hi @eldarkurtic 
Noring that since we are migrating one-shot functionality through sparsify, this enhancement should addressed.
Best, Jeannie / Neural Magic
