### ISSUE TITLE
Cannot get bounding box

### ISSUE THREAD

**Issue by OSMasterSoohwan** [neuralmagic/sparseml#787]
**Describe the bug**
Cannot get bounding box
I tried yolov5 webcam by two methods. The first is the default setting, the second is using branches and quantized weights.

python detect.py --source 0
python detect.py --weight ./runs/train/prunedquantized/weight/best.pt --source 0

I was able to get the webcam image, but in both cases I couldn't find the bounding box.

can i get some advice?

(Recently, when I ran the webcam on original YoloV5(https://github.com/ultralytics/yolov5),
 the bounding box was well drawn.)

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: 20.04
2. Python version [e.g. 3.7]: 3.8 (Conda)
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 
4. ML framework version(s) [e.g. torch 1.7.1]: torch 1.9.0 + cu111
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]: 

**To Reproduce**
Exact steps to reproduce the behavior:

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by KSGulin** [comment]
Hey @OSMasterSoohwan, thanks for reporting this issue. This is indeed a bug with the detect script and a fix is up at neuralmagic/yolov5#45
