### ISSUE TITLE
requirements.txt stalls

### ISSUE THREAD

**Issue by Tsardoz** [neuralmagic/sparseml#788]
Followed instructions using pip.
It stalls on tqdm - waited for hours and it could not find an appropriate version.
Tried on clean install under Ubuntu 20.04 with python 3.7, 3.8, 3.9 and 3.10 all with the same issue.

**Comment by dbogunowicz** [comment]
Hey @Tsardoz, this seems to not be a problem related to `sparseml` (just installed sparseml through pip from the scratch, same setup as yours). 

We will not be able to precisely point where the issue with your setup may be. However, in general when `pip install ...` freezes, there are a few things you may try with a high probability of success are:

1. Download the library manually e.g. with NumPy, go to `https://pypi.org/simple/numpy/` here and choose the .whl file of the version you'd like installed. Once it's downloaded you can manually install the .whl:

`pip install numpy-1.16.1-cp37-cp37m-win_amd64.whl`

2. Use `--no-cache-dir` argument: `pip install --no-cache-dir sparseml`

3. Disabling ipv6 networking on my device.

4. Reinstalling pip.

**Comment by dbogunowicz** [comment]
@Tsardoz, did you manage to fix the problem? Please give us feedback, so we can either help you further or close the issue.

**Comment by Tsardoz** [comment]
Sorry - yes I fixed it.
I did this by putting tqdm first but coworkers had no issue so I am not sure what the problem was. Please close.
Thanks.
