### ISSUE TITLE
DataParallel run with Transformers crashes

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#817]
**Describe the bug**
When running transformers experiments with knowledge distillation modifier in DataParallel mode and logging enabled (for example wandb), the run crashes in the first iteration with:
```
Boolean value of Tensor with more than one value is ambiguous
```
raised here: https://github.com/neuralmagic/sparseml/blob/25116d77c10e30dfabe541881f48c895e9ab2557/src/sparseml/pytorch/utils/logger.py#L573

Tracking the issue leads to model's output in DataParallel mode. Instead of the expected tensor with one value, the loss is a tensor with `n_gpu` values. In the standard HF transformers pipeline, this loss is averaged a bit later and thus doesn't help with logging that happens in the knowledge distillation modifier class.

**Expected behavior**
Runs shouldn't crash and the loss value should be handled properly.

**To Reproduce**
Run any transformers experiment with knowledge distillation in DataParallel mode and logging enabled (for example wandb).

**Comment by dbogunowicz** [comment]
@eldarkurtic we have seen that running with `n_gpu` > 1 may cause some bugs. We are actively working on that. Could you please share your CLI command (e.g. `sparseml.transformers.question_answering ... `), so I can look into the problem in more detail?
