### ISSUE TITLE
cannot export sparseml model into tensorflow .pb format

### ISSUE THREAD

**Issue by Adren98** [neuralmagic/sparseml#833]
**Describe the bug**
We cannot export sparseml model into tensorflow .pb format using export.py script.
```
python export.py --weights best_sparseml_yolov5s.pt --dynamic --include pb
```

**Expected behavior**

**Environment**
nclude all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Windows 10
2. Python version [e.g. 3.7]: 3.9.6
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]:c2fe8bde0e8dd97a6c675f12cbf40492ee51dcab
4. ML framework version(s) [e.g. torch 1.7.1]: tensor2.8, torch1.9.1
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**
Exact steps to reproduce the behavior:

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.
```
C:\Users\adren\OneDrive\Desktop\work\sparseml\integrations\ultralytics-yolov5\yolov5>python export.py --weights best_sparseml_yolov5s.pt --dynamic --include pb
C:\Users\adren\AppData\Local\Programs\Python\Python39\lib\site-packages\thop\utils.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
export: data=data\coco128.yaml, weights=['best_sparseml_yolov5s.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=True, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, remove_grid=False, include=['pb']
YOLOv5  v0.12-1-gc2fe8bd torch 1.9.1+cpu CPU

Fusing layers...
YOLOv5s summary: 224 layers, 7056607 parameters, 0 gradients, 16.3 GFLOPs
2022-05-30 15:57:30 sparseml.optim.manager INFO     Created recipe manager with metadata: {
 "__metadata__": null
}
Created recipe manager with metadata: {
 "__metadata__": null
}

PyTorch: starting from best_sparseml_yolov5s.pt with output shape (1, 25200, 7) (108.7 MB)
2022-05-30 15:57:33.768253: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-05-30 15:57:33.768485: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\adren\AppData\Local\Programs\Python\Python39\lib\site-packages\flatbuffers\compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

TensorFlow SavedModel: starting export with tensorflow 2.8.0...

                 from  n    params  module                                  arguments

TensorFlow SavedModel: export failure: 'QuantWrapper' object has no attribute 'weight'

TensorFlow GraphDef: starting export with tensorflow 2.8.0...

TensorFlow GraphDef: export failure: 'NoneType' object has no attribute 'inputs'
```

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by KSGulin** [comment]
Thanks for reporting this @Adren98. We currently only support exporting yolov5 models to onnx. There a few reasons for this, but the main ones are:
- Running the pruned models through the DeepSparse engine is the best (and in some cases only) way to realize the speed gains of high unstructured sparsity. The DeepSparse engine operates on onnx graphs, so we prioritize onnx support
- Supporting quantization across different formats can be non-trivial (as can be seen by the issue you're running into here)

In your use case, is .pb the final deployment target?

**Comment by Adren98** [comment]
Thank you for the reply, I was planning to get both .pb and .tflite

**Comment by KSGulin** [comment]
I see, thanks for sharing. Unfortunately running in those formats wouldn't allow for the performance improvements that come with unstructured sparsity. I would still recommend running with the DeepSparse engine on your target device instead. We currently support x86 and are working on adding ARM support, in case you're targeting mobile

**Comment by bdytx5** [comment]
Sorry if this is a dumb question, but why exactly do the other formats not allow for performance improvements?
