### ISSUE TITLE
BERT sparsification documentation

### ISSUE THREAD

**Issue by Grigor355** [neuralmagic/sparseml#840]
ReadMe of https://github.com/neuralmagic/sparseml/tree/main/integrations/huggingface-transformers gives an example of sparse transfer learning where one should call  sparseml.transformers.question_answering --args which works. But in https://github.com/neuralmagic/sparseml/blob/main/integrations/huggingface-transformers/tutorials/sparsifying_bert_using_recipes.md the command "python transformers/examples/pytorch/question-answering/run_qa.py " seems to be outdated, is it true? Thanks.

**Comment by KSGulin** [comment]
Yep that's correct. As you noticed, the sparsemle.transformers flow is the supported one and we're working on updating the documentation to reflect that. In the meanwhile, you should still be able to use the arguments in the existing documentation, you'll just need to swap out the base command.
