### ISSUE TITLE
my training of model is correct? 

### ISSUE THREAD

**Issue by akashAD98** [neuralmagic/sparseml#846]
im using coco128.yml & followed same steps to do trainig & im getting this inbetween training,may i know im doing something wrong? or its normal

what  kind of  information its showing?
<img width="588" alt="image" src="https://user-images.githubusercontent.com/62583018/172107132-d552b02d-9018-433a-a23f-a0515a755e51.png">

**Comment by akashAD98** [comment]
but im getting error for doing inference https://github.com/neuralmagic/deepsparse/issues/415

i used best.pth converted it to best.onnx . now i want to use deepspare for inference.but getting issue. please let me know whats wrong here. & Thanks for quick reply @KSGulin

**Comment by dbogunowicz** [comment]
I propose we keep this issue closed (I have created a fix in #847, very good remark @akashAD98) and move it to #415.

**Comment by dbogunowicz** [comment]
@akashAD98 please, let's stick to the relevant issue, and move this conversation to https://github.com/neuralmagic/deepsparse/issues/415  . It will be easier for us to follow and help you solve the problem.
