### ISSUE TITLE
SparseML create_pruning_recipe API erroring out on YOLOv3 tiny

### ISSUE THREAD

**Issue by markurtz** [neuralmagic/sparseml#944]
From community slack https://discuss-neuralmagic.slack.com/team/U03P31PUJGM: 

[Trunov Pavel](https://app.slack.com/team/U03P31PUJGM)
  [11:05 AM](https://discuss-neuralmagic.slack.com/archives/C020FPF3MQX/p1657728332430099)
Hello!
I'm trying to prune yolov3-tiny using sparseml. There is no recipe for tiny but I've figured out that it's possible to create a new one: [link](https://github.com/neuralmagic/sparseml/issues/396)
But I get error while converting:
/usr/local/lib/python3.7/dist-packages/sparseml/onnx/sparsification/model_info.py in _get_model_last_prunable_nodes(model)
    216             continue
    217         for parent in graph.get_node_parents(node):
--> 218             if any(output_id in seen_node_ids for output_id in parent.output):
    219                 continue
    220             stack.append(parent)

AttributeError: output
Could anyone help me?
sparseml._version_: 1.0.1
onnx._version_: 1.10.1
code:
from sparseml.sparsification import create_pruning_recipe
ONNX_FILE_PATH = "yolov3_tiny.onnx"
create_pruning_recipe(model=ONNX_FILE_PATH, save_path='./')
model (netron):
Inputs:
name: images
type: float32[1,3,416,416]
Outputs:
name: output
type: float32[Concatoutput_dim_0,Concatoutput_dim_1,Concatoutput_dim_2]
name: onnx::Sigmoid_124
type: float32[Transposeonnx::Sigmoid_124_dim_0,Transposeonnx::Sigmoid_124_dim_1,Transposeonnx::Sigmoid_124_dim_2,Transposeonnx::Sigmoid_124_dim_3,Transposeonnx::Sigmoid_124_dim_4]
name: onnx::Sigmoid_190
type: float32[Transposeonnx::Sigmoid_190_dim_0,3,Transposeonnx::Sigmoid_190_dim_2,Transposeonnx::Sigmoid_190_dim_3,11] (edited)

**Comment by betogulliver** [comment]
any updates on this issue?

I'm also trying to prune/quant a yolov3-tiny model.

(btw, great work! thanx)

**Comment by bfineran** [comment]
Hi @betogulliver we've released a new helper function, `create_recipe` for creating template recipes from pytorch models. let me know if this works.

https://github.com/neuralmagic/sparseml/blob/0cbd1122afb9fc647f02e5b629a9b5daadd3a962/src/sparseml/recipe_template/utils.py#L27

**Comment by jeanniefinks** [comment]
Hi @betogulliver 
Since some time has passed, we hope this solution works for you and we'll go ahead and close this issue. If you need to re-open this, please do! Thank you.
Jeannie / Neural Magic
