### ISSUE TITLE
Unexpected higher parameter count after sparsification

### ISSUE THREAD

**Issue by vipulnath** [neuralmagic/sparseml#962]
**Describe the bug**
Estimated parameter count 1.2 million but getting 7 million for original 7.2 million parametr model

**Expected behavior**
model expected to have 1.2 million
**Environment**
Include all relevant environment information:
1. OS : Ubuntu 20.04.3 LTS
2. Python version: 3.9.1

**To Reproduce**
1)yolov5 model
2)convert to onnx
3)made recipe file using sparsify , showed for 80 %sparsification, expected parameter 1.2 million form 7.2 million model
4)Followed github commands and san sparsification, after sparsification got 7 million paramters.

**Errors**
7 million parameters
![9](https://user-images.githubusercontent.com/46771630/182311457-671da5e1-b0be-46b4-a4a8-b895584ebb26.png)
![10](https://user-images.githubusercontent.com/46771630/182311477-45b77f29-3c29-40fc-be24-1471e747f518.png)
![11](https://user-images.githubusercontent.com/46771630/182311503-5953d7b1-a286-4a14-bb0c-ebbc9887a867.png)
![12](https://user-images.githubusercontent.com/46771630/182311522-f8281c8c-7909-430e-88a1-e25b027a01a4.png)
![14](https://user-images.githubusercontent.com/46771630/182311554-8f7b8666-a0fd-4da3-aefa-4b4176aeb253.png)

**Comment by KSGulin** [comment]
Hi @vipulnath, pruning does not explicitly remove parameters, but rather sets the pruned ones to 0. So the number of parameters the yolov5 library returns is not actually indicative of the set of "active" parameters in your model. You can manually check the sparsity of your model by looking at the weight tensor values, but I'd recommend deploying the model with [DeepSparse](https://github.com/neuralmagic/deepsparse) and tracking your inference speedups instead. Also, functionality to automatically calculate your model's sparsity will be released with a suite of new model-management features soon, so stay tuned (:

**Comment by SunHaozhe** [comment]
> unstructured pruning does not explicitly remove parameters, but rather sets the pruned ones to 0.

Can the SparseML library use sparse matrix implementation for unstructured pruning? I mean, instead of setting pruned parameters to 0, can the SparseML library turns the pruned parameter tensor in "sparse matrix" format in an hope to reduce model size and inference time?
