### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by LamnouarMohamed** [neuralmagic/sparseml#969]
Hi, 

I hope all is fine,
Thank you so much for sharing this repository, 
my question is can I apply this optimization on Yolox or just this optimization for bert and yolov5 ??

**Comment by dbogunowicz** [comment]
Hey @LamnouarMohamed.

We currently do not support yolox. However, given that we have had major success with sparsifying yolov5, and, at least at a first glance, yolox shares a lot of architectural similarities, I think it would a good idea to use our [Sparsify tool](https://github.com/neuralmagic/sparsify) to automatically optimize your model.

**Comment by LamnouarMohamed** [comment]
Hi @dbogunowicz 

thank you so much for reply,

if I don't have mistake,  you can correct me

 I think there is a huge difference between yolov5 and yolox, because yolov5 based on CNN, and yolox based on transformers, I think doesn't make sense to apply same recipe.

**Comment by dbogunowicz** [comment]
To close this issue: we do not have a specific sparsification integration for yolox. We are about to roll out sparsified yolov8, which, according to the benchmarks, is superior to yolox.
We are also working on the possibility for the users to sparsify any model, follow us to stay up-to-day with the developments!
