### ISSUE TITLE
Question - Add another task or model

### ISSUE THREAD

**Issue by s-gerrard48** [neuralmagic/sparseml#977]
Hi,

Is it possible to add new tasks or models? e.g. BART, text generation, seq2seq.
I guess it could be if I implement a new task and pipeline, but not sure if it is also supported by the inference engine (deepsparse).

If it is not supported now, do you have a plan for that sooner or later?

Thanks!

**Comment by dbogunowicz** [comment]
@s-gerrard48 Two things:
- you can always add your own custom pipeline in DeepSparse. Only two requirements are 1)  to use the `Pipeline` object (https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/pipeline.py) as an interface to your custom pipeline and also have the model in the onnx format (this is the model representation that DeepSparse support). Even though deepsparse engine is optimized for sparsified architectures, I would encourage you to use pipelines with the dense onnx model, it can still bring you some benefits
- as for support for sparsifying custom architectures, we are now laser-focused on delivering a tool that will allow the users to easily sparsify any custom model. Follow us on slack to be up-to-date with the development.

To clarify the information in your message:

- You can add a custom pipeline to DeepSparse by using the "Pipeline" object (https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/pipeline.py) as an interface and providing the model in ONNX format. Although DeepSparse is optimized for sparsified architectures, you can still get benefits from using dense ONNX models with the pipeline.
- Support for sparsifying custom architectures is a priority and updates on the development will be available on slack: https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-1oeyc4gqd-EPV4dlSGJ0mI0HytGM5ugA
